/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoCourse = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_439)"
    />
    <mask
      id="mask0_3502_439"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_439)"
      />
    </mask>
    <g mask="url(#mask0_3502_439)">
      <path
        d="M37.4194 22.3656C37.4194 12.1513 29.139 3.87097 18.9248 3.87097H0.43013V40.8602H37.4194V22.3656Z"
        fill="url(#paint2_linear_3502_439)"
      />
    </g>
    <g filter="url(#filter0_d_3502_439)">
      <path
        d="M20.0307 10.0583C24.5047 10.0583 28.1315 13.6852 28.1315 18.1592V26.2601H11.9298V10.0583H20.0307ZM23.6491 13.6227C23.2017 13.6227 22.839 13.9854 22.839 14.4328V23.6138C22.839 24.0612 23.2017 24.4239 23.6491 24.4239C24.0965 24.4239 24.4591 24.0612 24.4591 23.6138V14.4328C24.4591 13.9854 24.0965 13.6227 23.6491 13.6227Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M16.4015 25.6121C16.4015 25.2541 16.6917 24.964 17.0496 24.964H25.7013C27.0435 24.964 28.1315 26.0521 28.1315 27.3942C28.1315 28.7364 27.0435 29.8245 25.7013 29.8245H11.9298V28.0159H13.226V28.5284H25.7013C26.3276 28.5284 26.8354 28.0206 26.8354 27.3942C26.8354 26.7679 26.3276 26.2601 25.7013 26.2601H17.0496C16.6917 26.2601 16.4015 25.97 16.4015 25.6121Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M27.0515 25.2881H28.1316V27.4483H27.0515V25.2881Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_439"
        x="11.9298"
        y="10.0583"
        width="16.9035"
        height="20.5848"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_439"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_439"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_439"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8CD672" />
        <stop offset="1" stopColor="#59CBEF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_439"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_439"
        x1="32.2488"
        y1="9.63811"
        x2="0.430129"
        y2="40.8602"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoCourse.defaultProps = { size: 24 };

NeetoCourse.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
