/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoReplay = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_434)"
    />
    <mask
      id="mask0_3502_434"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_434)"
      />
    </mask>
    <g mask="url(#mask0_3502_434)">
      <path
        d="M37.4194 22.3656C37.4194 12.1513 29.1391 3.87097 18.9248 3.87097H0.430176V40.8602H37.4194V22.3656Z"
        fill="url(#paint2_linear_3502_434)"
      />
    </g>
    <g filter="url(#filter0_d_3502_434)">
      <path
        d="M23.7674 19.9308C24.0689 20.1048 24.0689 20.5399 23.7674 20.7139L18.2906 23.876C17.9892 24.05 17.6124 23.8325 17.6124 23.4844L17.6124 17.1603C17.6124 16.8123 17.9892 16.5947 18.2906 16.7687L23.7674 19.9308Z"
        fill="white"
      />
      <path
        d="M28.3346 14.9472C28.3759 15.2133 28.1465 15.4426 27.8805 15.4014L24.7555 14.9164C24.4337 14.8664 24.305 14.4722 24.5352 14.2419L27.1752 11.602C27.4054 11.3717 27.7997 11.5005 27.8496 11.8222L28.3346 14.9472Z"
        fill="white"
      />
      <path
        d="M20.273 12.0365C15.8005 12.0365 12.1749 15.6233 12.1749 20.0477C12.1749 24.4721 15.8005 28.0588 20.273 28.0588C23.5019 28.0588 26.2914 26.1894 27.5922 23.4805C27.8291 22.9871 28.4255 22.7772 28.9242 23.0116C29.423 23.2459 29.6352 23.8359 29.3983 24.3293C27.7788 27.7019 24.3025 30.0369 20.273 30.0369C14.6962 30.0369 10.1754 25.5646 10.1754 20.0477C10.1754 14.5308 14.6962 10.0585 20.273 10.0585C23.0982 10.0585 25.6539 11.2076 27.4854 13.0566C27.8719 13.4468 27.8655 14.073 27.4711 14.4553C27.0767 14.8376 26.4438 14.8312 26.0573 14.4411C24.5863 12.9561 22.5391 12.0365 20.273 12.0365Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_434"
        x="10.1754"
        y="10.0585"
        width="20.0216"
        height="20.7971"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_434"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_434"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_434"
        x1="-2.82529"
        y1="-3.81944"
        x2="44.0936"
        y2="45.2632"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.159672" stopColor="#83D6AE" />
        <stop offset="1" stopColor="#20C7BD" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_434"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_434"
        x1="32.2489"
        y1="9.63811"
        x2="0.430175"
        y2="40.8602"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoReplay.defaultProps = { size: 24 };

NeetoReplay.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
