/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoStore = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_438)"
    />
    <mask
      id="mask0_3502_438"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_438)"
      />
    </mask>
    <g mask="url(#mask0_3502_438)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430189V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_438)"
      />
    </g>
    <g filter="url(#filter0_d_3502_438)">
      <path
        d="M20.7018 11.2281C25.5464 11.2281 29.4737 15.1555 29.4737 20.0001V28.772H11.9298V11.2281H20.7018ZM16.9591 15.5555C16.9591 15.1679 16.6449 14.8538 16.2574 14.8538C15.8698 14.8538 15.5556 15.1679 15.5556 15.5555C15.5556 18.3977 17.8596 20.7017 20.7018 20.7017C23.544 20.7017 25.848 18.3977 25.848 15.5555C25.848 15.1679 25.5338 14.8538 25.1462 14.8538C24.7587 14.8538 24.4445 15.1679 24.4445 15.5555C24.4445 17.6225 22.7688 19.2982 20.7018 19.2982C18.6348 19.2982 16.9591 17.6225 16.9591 15.5555Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_438"
        x="11.9298"
        y="11.2281"
        width="18.2456"
        height="18.3625"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_438"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_438"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_438"
        x1="-8.07017"
        y1="-31.2866"
        x2="42.5146"
        y2="49.4737"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#3C5BFF" />
        <stop offset="0.732617" stopColor="#55ABE9" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_438"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_438"
        x1="32.2489"
        y1="9.63823"
        x2="0.430188"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoStore.defaultProps = { size: 24 };

NeetoStore.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
