/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoCi = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_447)"
    />
    <mask
      id="mask0_3502_447"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_447)"
      />
    </mask>
    <g mask="url(#mask0_3502_447)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430172V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_447)"
      />
    </g>
    <g filter="url(#filter0_d_3502_447)">
      <path
        d="M29.5766 9.5907H10.4234C9.96278 9.5907 9.59064 9.96283 9.59064 10.4234V29.5767C9.59064 30.0373 9.96278 30.4094 10.4234 30.4094H29.5766C30.0372 30.4094 30.4094 30.0373 30.4094 29.5767V10.4234C30.4094 9.96283 30.0372 9.5907 29.5766 9.5907ZM20.0286 20.1588L15.0321 24.3486C14.8968 24.4631 14.6912 24.3668 14.6912 24.1898V22.5582C14.6912 22.4983 14.7199 22.4384 14.7667 22.3994L17.6241 20.0001L14.7667 17.6007C14.7428 17.5818 14.7235 17.5577 14.7104 17.5301C14.6974 17.5026 14.6908 17.4724 14.6912 17.442V15.8103C14.6912 15.6333 14.8968 15.537 15.0321 15.6515L20.0286 19.8387C20.1301 19.922 20.1301 20.0755 20.0286 20.1588V20.1588ZM25.3088 24.1898C25.3088 24.3043 25.2203 24.398 25.1136 24.398H20.2993C20.1926 24.398 20.1041 24.3043 20.1041 24.1898V22.9407C20.1041 22.8262 20.1926 22.7325 20.2993 22.7325H25.1136C25.2203 22.7325 25.3088 22.8262 25.3088 22.9407V24.1898Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_447"
        x="9.59064"
        y="9.5907"
        width="21.5205"
        height="21.6374"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_447"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_447"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_447"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#EF8F59" />
        <stop offset="0.760417" stopColor="#FF85B8" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_447"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_447"
        x1="32.2489"
        y1="9.63823"
        x2="0.430171"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoCi.defaultProps = { size: 24 };

NeetoCi.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
