/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoForm = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <g clipPath="url(#clip0_3083_415)">
      <rect
        width="40"
        height="40"
        rx="10.7527"
        fill="url(#paint0_linear_3083_415)"
      />
      <mask
        id="mask0_3083_415"
        style={{maskType: "alpha"}}
        maskUnits="userSpaceOnUse"
        x="0"
        y="0"
        width="40"
        height="40"
      >
        <rect width="40" height="40" rx="10.7527" fill="#E5E5E5" />
      </mask>
      <g mask="url(#mask0_3083_415)"></g>
      <mask
        id="mask1_3083_415"
        style={{maskType: "alpha"}}
        maskUnits="userSpaceOnUse"
        x="0"
        y="0"
        width="40"
        height="40"
      >
        <rect
          width="40"
          height="40"
          rx="10.7527"
          fill="url(#paint1_linear_3083_415)"
        />
      </mask>
      <g mask="url(#mask1_3083_415)">
        <path
          d="M37.4194 22.3656C37.4194 12.1513 29.1391 3.87097 18.9248 3.87097H0.430145V40.8602H37.4194V22.3656Z"
          fill="url(#paint2_linear_3083_415)"
        />
      </g>
      <rect
        x="15.8585"
        y="18.1824"
        width="13.4982"
        height="3.68133"
        rx="1.84067"
        fill="white"
      />
      <rect
        x="15.8585"
        y="24.3179"
        width="10.4304"
        height="3.68133"
        rx="1.84067"
        fill="white"
      />
      <rect
        x="15.8585"
        y="12.0468"
        width="9.81689"
        height="3.68133"
        rx="1.84067"
        fill="white"
      />
      <circle cx="12.4839" cy="13.8874" r="1.84067" fill="white" />
      <circle cx="12.4839" cy="20.023" r="1.84067" fill="white" />
      <circle cx="12.4839" cy="26.1585" r="1.84067" fill="white" />
    </g>
    <defs>
      <linearGradient
        id="paint0_linear_3083_415"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FE8072" />
        <stop offset="1" stopColor="#F97290" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3083_415"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8886FF" />
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3083_415"
        x1="32.2488"
        y1="9.63811"
        x2="0.430144"
        y2="40.8602"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.375" stopColor="white" stopOpacity="0" />
      </linearGradient>
      <clipPath id="clip0_3083_415">
        <rect width="40" height="40" fill="white" />
      </clipPath>
    </defs>
  </svg>
);

NeetoForm.defaultProps = { size: 24 };

NeetoForm.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
