/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoGit = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 342 342" fill="none" {...other}>
    <rect
      width="342"
      height="342"
      rx="92.11"
      fill="url(#paint0_linear_3478_4236)"
    />
    <mask
      id="mask0_3478_4236"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="342"
      height="342"
    >
      <rect
        width="342"
        height="342"
        rx="92.11"
        fill="url(#paint1_linear_3478_4236)"
      />
    </mask>
    <g mask="url(#mask0_3478_4236)">
      <path
        d="M319.936 191.227C319.936 103.894 249.139 33.0977 161.807 33.0977H3.67773V349.356H319.936V191.227Z"
        fill="url(#paint2_linear_3478_4236)"
      />
    </g>
    <g filter="url(#filter0_d_3478_4236)">
      <path
        d="M96 96H145V133.852C138.618 135.969 134.023 141.993 134.041 149.083C134.06 156.144 138.649 162.124 145 164.231V193.183C138.612 195.282 134 201.295 134 208.386C134 217.222 141.163 224.386 150 224.386C158.837 224.386 166 217.222 166 208.386C166 201.295 161.388 195.282 155 193.183V164.258C157.09 163.578 158.99 162.479 160.602 161.061L177.718 170.943C177.513 171.971 177.408 173.034 177.41 174.122C177.433 182.959 184.615 190.104 193.452 190.081C202.289 190.058 209.433 182.875 209.41 174.039C209.387 165.202 202.205 158.058 193.369 158.081C189.239 158.091 185.479 159.666 182.647 162.242L165.679 152.445C165.919 151.335 166.044 150.182 166.041 149C166.023 141.909 161.394 135.907 155 133.825V96H171C212.421 96 246 129.579 246 171V246H96V96Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3478_4236"
        x="96"
        y="96"
        width="156"
        height="157"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="3" dy="4" />
        <feGaussianBlur stdDeviation="1.5" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3478_4236"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3478_4236"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3478_4236"
        x1="-235.5"
        y1="-258"
        x2="656"
        y2="678"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.176638" stopColor="#FF8B8B" />
        <stop offset="1" stopColor="#FF4E6E" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3478_4236"
        x1="-23.954"
        y1="-19.4627"
        x2="318.389"
        y2="522.498"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3478_4236"
        x1="275.728"
        y1="82.4067"
        x2="3.67773"
        y2="349.356"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoGit.defaultProps = { size: 24 };

NeetoGit.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
