/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoWireframe = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_433)"
    />
    <mask
      id="mask0_3502_433"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_433)"
      />
    </mask>
    <g mask="url(#mask0_3502_433)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_433)"
      />
    </g>
    <g filter="url(#filter0_d_3502_433)">
      <rect
        x="17.4165"
        y="11.345"
        width="11.2385"
        height="4.52123"
        rx="0.209479"
        fill="white"
      />
      <rect
        x="11.345"
        y="17.4165"
        width="11.2385"
        height="11.2385"
        rx="0.209479"
        fill="white"
      />
      <circle cx="13.6056" cy="13.6056" r="2.26061" fill="white" />
      <rect
        x="24.1335"
        y="28.6549"
        width="11.2385"
        height="4.52123"
        rx="0.209479"
        transform="rotate(-90 24.1335 28.6549)"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_433"
        x="11.345"
        y="11.345"
        width="18.0117"
        height="18.1288"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_433"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_433"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_433"
        x1="-2.82529"
        y1="-3.81944"
        x2="44.0936"
        y2="45.2632"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.159672" stopColor="#B49AFC" />
        <stop offset="1" stopColor="#6A67E8" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_433"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_433"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoWireframe.defaultProps = { size: 24 };

NeetoWireframe.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
