/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoReview = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_441)"
    />
    <mask
      id="mask0_3502_441"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_441)"
      />
    </mask>
    <g mask="url(#mask0_3502_441)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_441)"
      />
    </g>
    <g filter="url(#filter0_d_3502_441)">
      <path
        d="M28.3113 20.7727C27.0047 19.4662 24.8864 19.4662 23.5799 20.7727C22.2734 22.0792 22.2734 24.1975 23.5799 25.5041C24.8612 26.7854 26.9233 26.8101 28.2348 25.5782C28.2494 25.5609 28.2649 25.544 28.2813 25.5276C28.3012 25.5077 28.3218 25.4891 28.3432 25.4717C29.6177 24.1628 29.6071 22.0685 28.3113 20.7727ZM29.9561 26.06C31.3734 24.1195 31.2059 21.3826 29.4536 19.6303C27.5162 17.6929 24.375 17.6929 22.4375 19.6303C20.5001 21.5678 20.5001 24.709 22.4375 26.6464C24.1711 28.38 26.8685 28.5624 28.8049 27.1936L31.3697 29.7584C31.6852 30.0738 32.1966 30.0738 32.5121 29.7584C32.8275 29.4429 32.8275 28.9315 32.5121 28.616L29.9561 26.06Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M14.1767 25.2989L17.8406 28.9628L21.0497 25.7537C19.8549 23.6509 20.154 20.9296 21.9471 19.1366C23.479 17.6046 25.6885 17.1632 27.611 17.8122V14.3072C27.611 13.3355 27.225 12.4036 26.5379 11.7164C25.8507 11.0293 24.9188 10.6433 23.9471 10.6433H11.7341C10.7623 10.6433 9.83042 11.0293 9.14331 11.7164C8.45619 12.4036 8.07018 13.3355 8.07018 14.3072V21.635C8.07018 22.6067 8.45619 23.5387 9.14331 24.2258C9.83042 24.9129 10.7623 25.2989 11.7341 25.2989H14.1767ZM12.0481 15.4288C12.0481 14.9828 12.4097 14.6213 12.8557 14.6213H21.2303C21.6763 14.6213 22.0378 14.9828 22.0378 15.4288C22.0378 15.8748 21.6763 16.2364 21.2303 16.2364H12.8557C12.4097 16.2364 12.0481 15.8748 12.0481 15.4288ZM12.8557 17.6122C12.4097 17.6122 12.0481 17.9738 12.0481 18.4198C12.0481 18.8658 12.4097 19.2273 12.8557 19.2273H16.4448C16.8908 19.2273 17.2523 18.8658 17.2523 18.4198C17.2523 17.9738 16.8908 17.6122 16.4448 17.6122H12.8557Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_441"
        x="8.07018"
        y="10.6433"
        width="25.3802"
        height="20.1704"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_441"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_441"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_441"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#54CCAF" />
        <stop offset="1" stopColor="#59CBEF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_441"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_441"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoReview.defaultProps = { size: 24 };

NeetoReview.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
