/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoDesk = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7733"
      fill="url(#paint0_linear_3083_414)"
    />
    <mask
      id="mask0_3083_414"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7733"
        fill="url(#paint1_linear_3083_414)"
      />
    </mask>
    <g mask="url(#mask0_3083_414)">
      <path
        d="M37.4195 22.3656C37.4195 12.1513 29.1392 3.87097 18.9249 3.87097H0.430237V40.8602H37.4195V22.3656Z"
        fill="url(#paint2_linear_3083_414)"
      />
    </g>
    <g filter="url(#filter0_d_3083_414)">
      <path
        d="M9.33279 20.1427H13.5737C14.7447 20.1427 15.6941 21.0832 15.6941 22.2434V25.3945C15.6941 27.1348 14.2701 28.5456 12.5134 28.5456C10.7568 28.5456 9.33279 27.1348 9.33279 25.3945V20.1427Z"
        fill="white"
      />
      <path
        d="M24.1758 22.2434C24.1758 21.0832 25.1252 20.1427 26.2963 20.1427H30.5372V25.3945C30.5372 27.1348 29.1131 28.5456 27.3565 28.5456C25.5999 28.5456 24.1758 27.1348 24.1758 25.3945V22.2434Z"
        fill="white"
      />
      <path
        d="M9.38514 20.1427C9.91708 14.8348 14.4374 10.6893 19.935 10.6893C25.4326 10.6893 29.9529 14.8348 30.4848 20.1427H28.3511C27.8294 15.9976 24.2603 12.7901 19.935 12.7901C15.6097 12.7901 12.0406 15.9976 11.5189 20.1427H9.38514Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3083_414"
        x="9.33279"
        y="10.6893"
        width="22.0682"
        height="18.7202"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.431935" dy="0.431935" />
        <feGaussianBlur stdDeviation="0.215967" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.08 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3083_414"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3083_414"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3083_414"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FFD55C" />
        <stop offset="1" stopColor="#FD9437" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3083_414"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8886FF" />
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3083_414"
        x1="32.2489"
        y1="9.63811"
        x2="0.430236"
        y2="40.8602"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoDesk.defaultProps = { size: 24 };

NeetoDesk.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
