/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoSite = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_444)"
    />
    <mask
      id="mask0_3502_444"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_444)"
      />
    </mask>
    <g mask="url(#mask0_3502_444)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430206V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_444)"
      />
    </g>
    <g filter="url(#filter0_d_3502_444)">
      <path
        d="M27.625 11.9563L27.6505 11.9298H10.6432C10.0619 11.9298 9.59061 12.4011 9.59061 12.9824V14.152H24.0936V14.386H9.59061V26.9006C9.59061 27.4819 10.0619 27.9532 10.6432 27.9532H29.2397C29.8211 27.9532 30.2924 27.4819 30.2924 26.9006V14.5251L27.625 11.9563ZM27.0539 12.5495L21.9123 17.8884L24.6807 20.5544L29.8222 15.2155L27.0539 12.5495ZM21.3552 18.4954L20.44 22.1875L24.0951 21.134L21.3552 18.4954ZM11.345 13.0994C11.345 13.2931 11.1879 13.4502 10.9941 13.4502C10.8003 13.4502 10.6432 13.2931 10.6432 13.0994C10.6432 12.9056 10.8003 12.7485 10.9941 12.7485C11.1879 12.7485 11.345 12.9056 11.345 13.0994ZM12.0467 13.4502C12.2405 13.4502 12.3976 13.2931 12.3976 13.0994C12.3976 12.9056 12.2405 12.7485 12.0467 12.7485C11.853 12.7485 11.6959 12.9056 11.6959 13.0994C11.6959 13.2931 11.853 13.4502 12.0467 13.4502ZM13.4502 13.0994C13.4502 13.2931 13.2932 13.4502 13.0994 13.4502C12.9056 13.4502 12.7485 13.2931 12.7485 13.0994C12.7485 12.9056 12.9056 12.7485 13.0994 12.7485C13.2932 12.7485 13.4502 12.9056 13.4502 13.0994Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_444"
        x="9.59061"
        y="11.9298"
        width="21.4035"
        height="16.8422"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_444"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_444"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_444"
        x1="15.9649"
        y1="15.7895"
        x2="64.6784"
        y2="88.7134"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8176FF" />
        <stop offset="1" stopColor="#41BBFF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_444"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_444"
        x1="32.2489"
        y1="9.63823"
        x2="0.430205"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoSite.defaultProps = { size: 24 };

NeetoSite.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
