/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoMonitor = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_450)"
    />
    <mask
      id="mask0_3502_450"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_450)"
      />
    </mask>
    <g mask="url(#mask0_3502_450)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_450)"
      />
    </g>
    <g filter="url(#filter0_d_3502_450)">
      <path
        d="M28.5511 18.0353C28.6956 18.6669 28.7719 19.3245 28.7719 20V28.7719H11.3817L18.9474 21.2063L21.4194 23.6783C21.8305 24.0894 22.497 24.0894 22.908 23.6783L28.5511 18.0353ZM27.8734 16.1281C27.7902 16.1713 27.7122 16.2277 27.6425 16.2974L22.1637 21.7762L19.6917 19.3041C19.2806 18.8931 18.6141 18.893 18.203 19.3041L11.2281 26.2791V11.228H20C23.4548 11.228 26.4432 13.2253 27.8734 16.1281Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_450"
        x="11.2281"
        y="11.228"
        width="18.2456"
        height="18.3625"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_450"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_450"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_450"
        x1="-27.5439"
        y1="-30.1754"
        x2="68.9474"
        y2="82.3977"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.161458" stopColor="#17FFD5" />
        <stop offset="0.567708" stopColor="#46B5C5" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_450"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_450"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoMonitor.defaultProps = { size: 24 };

NeetoMonitor.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
