/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoPlanner = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7733C0 4.82338 4.82338 0 10.7733 0H29.2267C35.1766 0 40 4.82338 40 10.7733V29.2267C40 35.1766 35.1766 40 29.2267 40H10.7733C4.82338 40 0 35.1766 0 29.2267V10.7733Z"
      fill="url(#paint0_linear_3502_429)"
    />
    <mask
      id="mask0_3502_429"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect width="40" height="40" rx="10.7733" fill="#E5E5E5" />
    </mask>
    <g mask="url(#mask0_3502_429)"></g>
    <mask
      id="mask1_3502_429"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7733"
        fill="url(#paint1_linear_3502_429)"
      />
    </mask>
    <g mask="url(#mask1_3502_429)">
      <path
        d="M37.4195 22.3656C37.4195 12.1513 29.1391 3.87097 18.9248 3.87097H0.430222V40.8602H37.4195V22.3656Z"
        fill="url(#paint2_linear_3502_429)"
      />
    </g>
    <rect
      x="10.7526"
      y="10.7526"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="15.5174"
      y="10.7524"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="20.2823"
      y="10.7524"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="25.0472"
      y="10.7524"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="10.7525"
      y="15.5175"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="15.5174"
      y="15.5175"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="20.2823"
      y="15.5175"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="10.7525"
      y="20.2822"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="15.5174"
      y="20.2821"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <rect
      x="10.7525"
      y="25.0472"
      width="4.23545"
      height="4.23545"
      rx="1.05886"
      fill="white"
    />
    <defs>
      <linearGradient
        id="paint0_linear_3502_429"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#4DC8C3" />
        <stop offset="1" stopColor="#52A9C6" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_429"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8886FF" />
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_429"
        x1="32.2489"
        y1="9.63811"
        x2="0.430221"
        y2="40.8602"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.12" />
        <stop offset="0.345284" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoPlanner.defaultProps = { size: 24 };

NeetoPlanner.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
