/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoTestify = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_445)"
    />
    <mask
      id="mask0_3502_445"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_445)"
      />
    </mask>
    <g mask="url(#mask0_3502_445)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_445)"
      />
    </g>
    <g filter="url(#filter0_d_3502_445)">
      <path
        d="M30.4576 28.1426L27.6617 25.3801C27.38 25.8328 27.0447 26.2572 26.6572 26.6433C26.2665 27.0344 25.8379 27.3732 25.3801 27.6569L28.1922 30.4352C28.8225 31.0587 29.8363 31.0532 30.4631 30.4274C30.4657 30.4248 30.4679 30.4226 30.4702 30.4206C31.0992 29.7913 31.0908 28.7683 30.4576 28.1426Z"
        fill="white"
      />
      <path
        d="M27.9532 19.1228C27.9532 23.9933 23.98 27.9532 19.0643 27.9532C14.1487 27.9532 10.1754 23.9933 10.1754 19.1228C10.1754 14.2523 14.1487 10.2924 19.0643 10.2924C23.98 10.2924 27.9532 14.2523 27.9532 19.1228Z"
        stroke="white"
        strokeWidth="2.33918"
      />
      <path
        d="M22.3202 15.6518L21.2851 16.6786L23.2017 19.0643L21.2851 21.453L22.3202 22.4798L25.0292 19.0643L22.3202 15.6518ZM17.0775 16.6757L16.0424 15.6496L13.3333 19.0643L16.0424 22.4769L17.0775 21.4501L15.1608 19.0643L17.0775 16.6757ZM17.7193 22.6901H19.1813L20.6433 15.4386H19.1813L17.7193 22.6901Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_445"
        x="9.00584"
        y="9.1228"
        width="22.6332"
        height="22.5957"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_445"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_445"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_445"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FFF27A" />
        <stop offset="0.822917" stopColor="#FF9E45" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_445"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_445"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoTestify.defaultProps = { size: 24 };

NeetoTestify.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
