/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoAnalytics = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_428)"
    />
    <mask
      id="mask0_3502_428"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="20"
        fill="url(#paint1_linear_3502_428)"
      />
    </mask>
    <g mask="url(#mask0_3502_428)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430172V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_428)"
      />
    </g>
    <g filter="url(#filter0_d_3502_428)">
      <rect
        x="9.47374"
        y="17.6344"
        width="2.49143"
        height="4.36"
        fill="white"
      />
      <rect
        x="12.9618"
        y="14.5201"
        width="2.49143"
        height="7.47429"
        fill="white"
      />
      <path
        d="M16.4497 10.4092H18.9412V21.9943H16.4497V10.4092Z"
        fill="white"
      />
      <path
        d="M23.9156 24.2394C24.4934 23.7672 25.3445 23.8528 25.8167 24.4305L30.2214 29.8198C30.6936 30.3976 30.608 31.2487 30.0303 31.7209C29.4525 32.1931 28.6014 32.1075 28.1292 31.5298L23.7245 26.1405C23.2523 25.5627 23.3379 24.7116 23.9156 24.2394Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M26.3213 19.1189C26.3213 15.8239 23.6685 13.1485 20.3821 13.1119V10.4098C25.1608 10.4464 29.0233 14.3316 29.0233 19.1189C29.0233 22.0022 27.6208 24.5582 25.4667 26.1411C24.0237 27.2016 22.24 27.8284 20.3139 27.8284C17.4857 27.8284 14.9722 26.479 13.3834 24.3944C13.1593 24.1004 12.9534 23.7915 12.7674 23.4695H16.171C17.25 24.4975 18.7083 25.1264 20.3139 25.1264C21.6452 25.1264 22.8718 24.6949 23.8667 23.9638C25.3578 22.868 26.3213 21.1061 26.3213 19.1189Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_428"
        x="9.47374"
        y="10.4092"
        width="27.0526"
        height="28.6167"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="3" dy="4" />
        <feGaussianBlur stdDeviation="1.5" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_428"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_428"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_428"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#63D9FE" />
        <stop offset="0.798939" stopColor="#8588FF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_428"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_428"
        x1="32.2489"
        y1="9.63823"
        x2="0.430171"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoAnalytics.defaultProps = { size: 24 };

NeetoAnalytics.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
