/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoCrm = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M0 10.7731C0 4.82328 4.82328 0 10.7731 0H29.2269C35.1767 0 40 4.82328 40 10.7731V29.2269C40 35.1767 35.1767 40 29.2269 40H10.7731C4.82328 40 0 35.1767 0 29.2269V10.7731Z"
      fill="url(#paint0_linear_3502_431)"
    />
    <mask
      id="mask0_3502_431"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_431)"
      />
    </mask>
    <g mask="url(#mask0_3502_431)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_431)"
      />
    </g>
    <g filter="url(#filter0_d_3502_431)">
      <path
        d="M15.6893 18.7462C14.9969 18.0538 13.8743 18.0538 13.1819 18.7462C12.4896 19.4386 12.4896 20.5612 13.1819 21.2535C13.8743 21.9459 14.9969 21.9459 15.6893 21.2535C16.3816 20.5612 16.3816 19.4386 15.6893 18.7462ZM17.1172 17.3183C15.6362 15.8373 13.235 15.8373 11.754 17.3183C10.273 18.7993 10.273 21.2005 11.754 22.6815C13.235 24.1625 15.6362 24.1625 17.1172 22.6815C18.5982 21.2005 18.5982 18.7993 17.1172 17.3183Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M26.818 13.182C26.1256 12.4896 25.003 12.4896 24.3107 13.182C23.6183 13.8744 23.6183 14.997 24.3107 15.6893C25.003 16.3817 26.1256 16.3817 26.818 15.6893C27.5104 14.997 27.5104 13.8744 26.818 13.182ZM28.2459 11.7541C26.7649 10.2731 24.3637 10.2731 22.8827 11.7541C21.4017 13.2351 21.4017 15.6363 22.8827 17.1173C24.3637 18.5983 26.7649 18.5983 28.2459 17.1173C29.7269 15.6363 29.7269 13.2351 28.2459 11.7541Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M26.818 24.3104C26.1256 23.618 25.003 23.618 24.3107 24.3104C23.6183 25.0028 23.6183 26.1254 24.3107 26.8177C25.003 27.5101 26.1256 27.5101 26.818 26.8177C27.5104 26.1254 27.5104 25.0028 26.818 24.3104ZM28.2459 22.8825C26.7649 21.4015 24.3637 21.4015 22.8827 22.8825C21.4017 24.3635 21.4017 26.7647 22.8827 28.2457C24.3637 29.7267 26.7649 29.7267 28.2459 28.2457C29.7269 26.7647 29.7269 24.3635 28.2459 22.8825Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M23.9914 15.2183C24.2408 15.7171 24.0386 16.3236 23.5398 16.5729L17.3631 19.6613C16.8644 19.9107 16.2578 19.7085 16.0085 19.2097C15.7591 18.711 15.9612 18.1045 16.46 17.8551L22.6367 14.7667C23.1355 14.5173 23.742 14.7195 23.9914 15.2183Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M16.0085 20.7899C16.2578 20.2912 16.8644 20.089 17.3631 20.3384L23.5398 23.4267C24.0386 23.6761 24.2408 24.2826 23.9914 24.7814C23.742 25.2802 23.1355 25.4823 22.6367 25.233L16.46 22.1446C15.9612 21.8952 15.7591 21.2887 16.0085 20.7899Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_431"
        x="10.6432"
        y="10.6433"
        width="19.4152"
        height="19.5318"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_431"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_431"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_431"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.305309" stopColor="#75DCFD" />
        <stop offset="0.930745" stopColor="#597DEF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_431"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_431"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoCrm.defaultProps = { size: 24 };

NeetoCrm.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
