/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoSocial = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_446)"
    />
    <mask
      id="mask0_3502_446"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_446)"
      />
    </mask>
    <g mask="url(#mask0_3502_446)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430168V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_446)"
      />
    </g>
    <g filter="url(#filter0_d_3502_446)">
      <path
        d="M30.0344 13.6142C30.0278 11.5809 28.3782 9.94153 26.3449 9.94153H13.5141C12.5336 9.94153 11.5934 10.3266 10.9013 11.0213C10.2087 11.7156 9.82148 12.6545 9.82458 13.6351L9.85604 23.4551C9.86224 25.4879 11.5123 27.1265 13.5456 27.1265H17.1824L18.9131 29.6082C19.1457 29.9418 19.5263 30.1403 19.9326 30.1412C20.3389 30.1425 20.7204 29.9454 20.9548 29.6122L22.7045 27.1273H26.3759C27.3564 27.1273 28.2967 26.7423 28.9883 26.0476C29.6809 25.3528 30.0686 24.4161 30.0655 23.4356L30.0344 13.6142ZM19.9446 12.1304C21.8454 12.1304 23.3864 13.6714 23.3864 15.5713C23.3864 17.4726 21.845 19.0127 19.9446 19.0127C18.0442 19.0127 16.5036 17.4726 16.5036 15.5713C16.504 13.6714 18.0446 12.1304 19.9446 12.1304ZM25.4255 24.1583C25.4255 24.5827 25.0817 24.9266 24.6572 24.9266H15.2306C14.8057 24.9266 14.4614 24.5827 14.4614 24.1578C14.4614 22.2308 16.0153 20.665 17.9423 20.665H21.9482C22.8738 20.665 23.7555 21.035 24.41 21.6894C25.0644 22.3438 25.4255 23.2335 25.4255 24.1583Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_446"
        x="9.82456"
        y="9.94153"
        width="20.9427"
        height="21.0184"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_446"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_446"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_446"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#4A9CE9" />
        <stop offset="1" stopColor="#81D2F4" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_446"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_446"
        x1="32.2489"
        y1="9.63823"
        x2="0.430167"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoSocial.defaultProps = { size: 24 };

NeetoSocial.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
