/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoDeploy = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_443)"
    />
    <mask
      id="mask0_3502_443"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_443)"
      />
    </mask>
    <g mask="url(#mask0_3502_443)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430176V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_443)"
      />
    </g>
    <g filter="url(#filter0_d_3502_443)">
      <path
        d="M11.6996 21.274C13.2684 19.0157 14.1912 17.5609 14.8641 16.4857C12.2784 16.7144 9.80005 19.9317 9.80005 19.9317L11.5067 21.6383C11.5562 21.5121 11.6195 21.3896 11.6996 21.274Z"
        fill="white"
      />
      <path
        d="M18.3635 28.4948L20.069 30.2002C20.069 30.2002 23.2862 27.722 23.5149 25.1365C22.4401 25.809 20.9857 26.7315 18.7267 28.3007C18.6125 28.38 18.4907 28.4448 18.3635 28.4948Z"
        fill="white"
      />
      <path
        d="M15.7697 27.613C15.4769 27.7313 15.1892 27.857 14.8892 27.9573C14.0879 28.2251 13.2627 28.406 12.426 28.5215C12.0753 28.5699 11.7214 28.6109 11.3668 28.6378C11.3702 28.594 11.3735 28.5502 11.3772 28.5065C11.4503 27.654 11.58 26.806 11.7896 25.9758C11.8905 25.5752 12.0194 25.1858 12.1577 24.7969C12.2437 24.5551 12.351 24.3237 12.4593 24.0923L12.2716 23.9048C11.8543 24.1851 11.4914 24.5393 11.1834 24.9401C10.7274 25.5335 10.3856 26.2058 10.1467 26.9142C9.88999 27.6749 9.73692 28.4805 9.71309 29.2836C9.70971 29.3964 9.70196 29.5117 9.71944 29.6237C9.74195 29.7683 9.80545 29.9051 9.90085 30.016C9.99527 30.1257 10.1195 30.2085 10.2573 30.253C10.3729 30.2902 10.4891 30.2909 10.609 30.29C11.3381 30.2839 12.0785 30.1572 12.7764 29.9499C14.0528 29.5706 15.3414 28.8572 16.0968 27.7298L15.9141 27.5473C15.8663 27.5698 15.8183 27.5919 15.7697 27.613Z"
        fill="white"
      />
      <path
        d="M29.9683 10.0327C29.9683 10.0327 29.9681 10.0327 29.968 10.0325C29.8352 9.89979 29.6552 9.82544 29.4678 9.82544C29.4632 9.82544 29.4585 9.82551 29.4538 9.82557C27.1756 9.87026 21.5547 10.2964 18.5697 13.2816C17.2146 14.6367 16.7742 15.342 15.8089 16.8879C15.1137 18.0008 14.1619 19.5253 12.4225 22.0289C12.2271 22.3103 12.2611 22.6912 12.5033 22.9333L17.0669 27.4969C17.2039 27.6339 17.3852 27.7044 17.5677 27.7044C17.708 27.7044 17.849 27.6628 17.9713 27.5779C20.4759 25.838 21.9997 24.8865 23.1123 24.1916C24.658 23.2263 25.3635 22.7858 26.7188 21.4305C29.7092 18.4401 30.1323 12.8229 30.1752 10.5466C30.179 10.3544 30.1042 10.1689 29.9683 10.0327ZM24.6837 18.6436C23.765 19.5623 22.2755 19.5623 21.3568 18.6436C20.4379 17.7248 20.438 16.2355 21.3569 15.3167C22.2755 14.398 23.765 14.3978 24.6837 15.3166C25.6022 16.2353 25.6024 17.7249 24.6837 18.6436Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_443"
        x="9.70844"
        y="9.82544"
        width="21.1687"
        height="21.2834"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_443"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_443"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_443"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.244792" stopColor="#14D1A4" />
        <stop offset="1" stopColor="#67BDE2" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_443"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_443"
        x1="32.2489"
        y1="9.63823"
        x2="0.430175"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoDeploy.defaultProps = { size: 24 };

NeetoDeploy.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
