/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Zoom = ({ size, ...other }) => (
  <svg viewBox="0 0 48 48" width={size} height={size} {...other}>
    <circle cx="24" cy="24" r="20" fill="#2196f3" />
    <path
      fill="#fff"
      d="M29,31H14c-1.657,0-3-1.343-3-3V17h15c1.657,0,3,1.343,3,3V31z"
    />
    <polygon fill="#fff" points="37,31 31,27 31,21 37,17" />
  </svg>
);

Zoom.defaultProps = { size: 24 };

Zoom.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
