import React from "react";

type LogoProps = { size?: string | number } & React.SVGProps<SVGSVGElement>;

export const Neeto: React.FC<LogoProps>;
export const NeetoCal: React.FC<LogoProps>;
export const NeetoChangelog: React.FC<LogoProps>;
export const NeetoChat: React.FC<LogoProps>;
export const NeetoCi: React.FC<LogoProps>;
export const NeetoCode: React.FC<LogoProps>;
export const NeetoCourse: React.FC<LogoProps>;
export const NeetoCrm: React.FC<LogoProps>;
export const NeetoDeploy: React.FC<LogoProps>;
export const NeetoDesk: React.FC<LogoProps>;
export const NeetoForm: React.FC<LogoProps>;
export const NeetoGit: React.FC<LogoProps>;
export const NeetoInvisible: React.FC<LogoProps>;
export const NeetoInvoice: React.FC<LogoProps>;
export const NeetoKb: React.FC<LogoProps>;
export const NeetoPlanner: React.FC<LogoProps>;
export const NeetoPlaydash: React.FC<LogoProps>;
export const NeetoPublish: React.FC<LogoProps>;
export const NeetoQuiz: React.FC<LogoProps>;
export const NeetoRecord: React.FC<LogoProps>;
export const NeetoReplay: React.FC<LogoProps>;
export const NeetoRunner: React.FC<LogoProps>;
export const NeetoSeo: React.FC<LogoProps>;
export const NeetoSite: React.FC<LogoProps>;
export const NeetoTestify: React.FC<LogoProps>;
export const NeetoWireframe: React.FC<LogoProps>;
