/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const AddRectangle = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 13 11" fill="none" {...other}>
    <path
      d="M11.6667 4.33333V2.33333C11.6667 1.97971 11.5262 1.64057 11.2761 1.39052C11.0261 1.14048 10.687 1 10.3333 1H2.33333C1.97971 1 1.64057 1.14048 1.39052 1.39052C1.14048 1.64057 1 1.97971 1 2.33333V5.66667C1 6.02029 1.14048 6.35943 1.39052 6.60948C1.64057 6.85952 1.97971 7 2.33333 7H5.66667M10 6V10M8 8H12"
      stroke={color}
      strokeWidth="1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

AddRectangle.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

AddRectangle.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
