/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Bank = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M11.8276 3.20011C11.9241 3.10813 12.0759 3.10813 12.1724 3.20011L18.3332 9.06899C18.4966 9.22464 18.3864 9.5 18.1607 9.5H5.83928C5.61361 9.5 5.50345 9.22464 5.66684 9.06899L11.8276 3.20011Z"
      fill={color}
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <line
      x1="6.75"
      y1="17.25"
      x2="6.75"
      y2="12.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="10.0833"
      y1="17.25"
      x2="10.0833"
      y2="12.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="13.4167"
      y1="17.25"
      x2="13.4167"
      y2="12.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="16.75"
      y1="17.25"
      x2="16.75"
      y2="12.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="5.54999"
      y1="20.25"
      x2="18.05"
      y2="20.25"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
  </svg>
);

Bank.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Bank.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
