/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Category = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 32 32" fill="none" {...other}>
    <path
      d="M4 12.0001L9.33333 6.66675M9.33333 6.66675L14.6667 12.0001M9.33333 6.66675V25.3334M28 20.0001L22.6667 25.3334M22.6667 25.3334L17.3333 20.0001M22.6667 25.3334V6.66675"
      stroke={color}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Category.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Category.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
