/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const CenterAlign = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 18 19" fill="none" {...other}>
    <g clipPath="url(#clip0_1047_4338)">
      <rect
        x="3"
        y="11.3335"
        width="11.5714"
        height="3.85714"
        rx="1"
        fill={color}
      />
      <mask id="path-2-inside-1_1047_4338" fill={color}>
        <rect x="4.5" y="6.19043" width="9" height="3.85714" rx="1" />
      </mask>
      <rect
        x="4.5"
        y="6.19043"
        width="9"
        height="3.85714"
        rx="1"
        stroke={color}
        mask="url(#path-2-inside-1_1047_4338)"
        strokeWidth="3"
      />
      <line
        x1="9"
        y1="9.61914"
        x2="9"
        y2="17.1191"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <line
        x1="9"
        y1="2.86914"
        x2="9"
        y2="6.61914"
        stroke={color}
        strokeWidth={strokeWidth}
      />
    </g>
    <defs>
      <clipPath id="clip0_1047_4338">
        <rect
          width="18"
          height="18"
          fill={color}
          transform="translate(0 0.619141)"
        />
      </clipPath>
    </defs>
  </svg>
);

CenterAlign.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

CenterAlign.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
