/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const ChatEmpty = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 14 14" fill="none" {...other}>
    <path
      d="M1 12.3333L1.86667 9.7333C1.11763 8.62549 0.846662 7.31358 1.10415 6.04151C1.36163 4.76943 2.13004 3.62375 3.26651 2.81749C4.40298 2.01122 5.83017 1.59924 7.28273 1.65813C8.73528 1.71703 10.1143 2.24279 11.1635 3.13768C12.2127 4.03256 12.8606 5.23567 12.9867 6.52329C13.1128 7.81092 12.7086 9.09546 11.8492 10.1381C10.9899 11.1807 9.73377 11.9104 8.31453 12.1915C6.89529 12.4727 5.40947 12.2862 4.13333 11.6666L1 12.3333Z"
      stroke={color}
      strokeWidth="1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

ChatEmpty.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

ChatEmpty.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
