/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Flag = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 12 13" fill="none" {...other}>
    <path
      d="M1.33337 7.33331H10.6667L7.66671 4.33331L10.6667 1.33331H1.33337V12"
      stroke={color}
      strokeWidth="1"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Flag.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Flag.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
