/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const ImageUpload = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M20.9998 9.99999V17C20.9998 19.2 19.1998 21 16.9998 21H6.99979L6.98979 20.999C4.77979 20.989 2.98979 19.199 2.98979 16.989V6.98899C2.97979 4.77899 4.77979 2.97899 6.97979 2.97899H12.9798"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M3 13L4.29 11.7H4.28C5.22 10.75 6.74 10.75 7.68 11.69L11.97 15.98"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M7.00293 21L13.2929 14.7V14.69C14.2329 13.74 15.7529 13.74 16.6929 14.69L20.6229 18.62"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M17.9995 3L15.4995 5.5"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M20.5 5.5L18 3"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M18 3V8"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

ImageUpload.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

ImageUpload.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
