/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoReplay = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M11.206 9.11501L14.9 11.3C15.432 11.615 15.432 12.385 14.9 12.7L11.205 14.885C10.663 15.206 9.978 14.815 9.978 14.185V9.81501C9.978 9.18501 10.664 8.79401 11.206 9.11501V9.11501Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M7.327 17.364L5.636 18.364C9.151 21.879 14.849 21.879 18.364 18.364C20.861 15.867 21.575 12.27 20.523 9.13401M16.673 6.63601L18.364 5.63601C14.849 2.12101 9.151 2.12101 5.636 5.63601C3.139 8.13301 2.425 11.731 3.477 14.866"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

NeetoReplay.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

NeetoReplay.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
