/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoWireframe = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 19 21" fill="none" {...other}>
    <path
      d="M1.5 9.13701V4.43701V4.43696C1.49892 3.33047 2.39357 2.43184 3.50005 2.42801V2.42801C4.60462 2.42801 5.50005 3.32344 5.50005 4.42801V4.42801V9.00501M1.5 5.91001H5.5H1.5Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M8.25 9V1H13V9"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M14 16H15.5V16C16.8807 16 18 14.8807 18 13.5V12.055C18 10.9504 17.1046 10.055 16 10.055H13.833"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M2 9H12.833V9C13.3853 9 13.833 9.44771 13.833 10V16.333V16.333C13.833 18.3578 12.1918 19.9995 10.167 20H4.667V20C2.64177 20 1 18.3582 1 16.333V10V10C1 9.44771 1.44771 9 2 9V9Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12.25 3.84H10.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12.25 6.34H11.75"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

NeetoWireframe.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

NeetoWireframe.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
