/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Pause = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <line
      x1="9"
      y1="6"
      x2="9"
      y2="17"
      stroke={color}
      strokeWidth="2"
      strokeLinecap="round"
    />
    <line
      x1="15"
      y1="6"
      x2="15"
      y2="17"
      stroke={color}
      strokeWidth="2"
      strokeLinecap="round"
    />
  </svg>
);

Pause.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Pause.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
