/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const SendPlane = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M10.88 12H5.39001"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M5.24292 3.6301L19.835 10.9243V10.9243C20.4291 11.2211 20.6701 11.9434 20.3732 12.5375C20.2568 12.7704 20.0679 12.9593 19.835 13.0757L5.24292 20.3698V20.3698C4.64875 20.667 3.92618 20.4262 3.62902 19.832C3.49802 19.5701 3.46708 19.2694 3.542 18.9863L5.39248 12L3.542 5.01366V5.01366C3.37205 4.37142 3.75492 3.71303 4.39715 3.54308C4.68027 3.46816 4.98099 3.4991 5.24292 3.6301L5.24292 3.6301Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

SendPlane.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

SendPlane.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
