/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Tablet = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} fill="none" viewBox="0 0 24 24" {...other}>
    <path
      stroke={color}
      d="M17.895 3H6.105C5.49473 3 5 3.49473 5 4.105V19.895C5 20.5053 5.49473 21 6.105 21H17.895C18.5053 21 19 20.5053 19 19.895V4.105C19 3.49473 18.5053 3 17.895 3Z"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
    />
    <path
      stroke={color}
      d="M9.5 18.5H14.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={strokeWidth}
    />
  </svg>
);

Tablet.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Tablet.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
