/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Tablet = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 25 24" fill="none" {...other}>
    <path
      d="M18.4184 3H6.62844C6.01816 3 5.52344 3.49473 5.52344 4.105V19.895C5.52344 20.5053 6.01816 21 6.62844 21H18.4184C19.0287 21 19.5234 20.5053 19.5234 19.895V4.105C19.5234 3.49473 19.0287 3 18.4184 3Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M10.0234 18.5H15.0234"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Tablet.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Tablet.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
