/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Text = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <g clipPath="url(#clip0_861:2152)">
      <path
        d="M15.315 15.014L12 8.01398L8.68401 15.013"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M9.347 13.613H14.65"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M18 21.014H6C4.343 21.014 3 19.671 3 18.014V6.01398C3 4.35698 4.343 3.01398 6 3.01398H18C19.657 3.01398 21 4.35698 21 6.01398V18.014C21 19.671 19.657 21.014 18 21.014Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </g>
    <defs>
      <clipPath id="clip0_861:2152">
        <rect width="24" height="24" fill={color} />
      </clipPath>
    </defs>
  </svg>
);

Text.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Text.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
