/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function AddMenu(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M19.3742 12.5C19.3742 12.0858 19.0384 11.75 18.6242 11.75C18.21 11.75 17.8742 12.0858 17.8742 12.5V14.6242H15.75C15.3358 14.6242 15 14.96 15 15.3742C15 15.7884 15.3358 16.1242 15.75 16.1242H17.8742V18.2483C17.8742 18.6626 18.21 18.9983 18.6242 18.9983C19.0384 18.9983 19.3742 18.6626 19.3742 18.2483V16.1242H21.4983C21.9126 16.1242 22.2483 15.7884 22.2483 15.3742C22.2483 14.96 21.9126 14.6242 21.4983 14.6242H19.3742V12.5Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <line
        x1="3.75"
        y1="7.25"
        x2="20.25"
        y2="7.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="3.75"
        y1="11.25"
        x2="14.25"
        y2="11.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="3.75"
        y1="15.25"
        x2="10.25"
        y2="15.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
    </svg>
  );
}

AddMenu.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

AddMenu.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
