/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Archive(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 16 16" fill="none" height={size} width={size} {...other}>
      <path
        d="M2 12.6668V10.3335C2 9.78121 2.44772 9.3335 3 9.3335H4.25267C4.5177 9.33355 4.77187 9.43882 4.95933 9.62616L5.61 10.2768C5.85994 10.5265 6.19873 10.6668 6.552 10.6668H9.44733C9.80116 10.6669 10.1405 10.5264 10.3907 10.2762L10.9433 9.7235C11.1933 9.47384 11.5321 9.33357 11.8853 9.3335H13C13.5523 9.3335 14 9.78121 14 10.3335V12.6668C14 13.4032 13.403 14.0002 12.6667 14.0002H3.33333C2.59695 14.0002 2 13.4032 2 12.6668Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M3.33301 9.33333V3.33333C3.33301 2.59695 3.92996 2 4.66634 2H11.333C12.0694 2 12.6663 2.59695 12.6663 3.33333V9.33333"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Archive.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Archive.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
