/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Building(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M5.26999 7C5.26999 5.75736 6.27735 4.75 7.51999 4.75H11.9917C13.2343 4.75 14.2417 5.75736 14.2417 7V19.25H5.26999V7Z"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <path
        d="M14.9717 20L18 20H19.5V18.5V12.6216C19.5 10.9648 18.1568 9.62163 16.5 9.62163H14.9717V11.1216H16.5C17.3284 11.1216 18 11.7932 18 12.6216V18.5H14.9717V20Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <line
        x1="2.25"
        y1="19.25"
        x2="21.75"
        y2="19.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="5.75"
        y1="9.25"
        x2="8.25"
        y2="9.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="7.75"
        y1="9.25"
        x2="11.25"
        y2="9.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="5.75"
        y1="12.25"
        x2="8.25"
        y2="12.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="7.75"
        y1="12.25"
        x2="11.25"
        y2="12.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
    </svg>
  );
}

Building.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Building.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
