/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function BurgerMenu(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <line
        x1="3"
        y1="7.25"
        x2="21"
        y2="7.25"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <line
        x1="3"
        y1="11.25"
        x2="15"
        y2="11.25"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <line
        x1="3"
        y1="15.25"
        x2="11"
        y2="15.25"
        stroke={color}
        strokeWidth={strokeWidth}
      />
    </svg>
  );
}

BurgerMenu.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

BurgerMenu.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
