/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function CannedResponses(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 32 32" fill="none" height={size} width={size} {...other}>
      <path
        d="M12 22H4V8H16V6H4C3.46957 6 2.96086 6.21071 2.58579 6.58579C2.21071 6.96086 2 7.46957 2 8V22C2 22.5304 2.21071 23.0391 2.58579 23.4142C2.96086 23.7893 3.46957 24 4 24H12V22ZM22 13.414L28 7.414V12H30V4H22V6H26.586L20.586 12L22 13.414ZM13.4953 30L11.8953 28.8L17 22H24V16H26V22C25.9994 22.5302 25.7885 23.0386 25.4135 23.4135C25.0386 23.7885 24.5302 23.9994 24 24H18L13.4953 30Z"
        fill={color}
      />
    </svg>
  );
}

CannedResponses.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

CannedResponses.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
