/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function ChatOffline(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M19.394 14C18.5 16 15.5 18.48 12 18.48C11.5 18.48 10.8864 18.4264 10.339 18.321L7.2 19.867C7.2 18.797 7.2 17.778 7.2 17.022C5.23493 15.7498 4.03448 13.5807 4 11.24C4 7.223 7.6 4 12 4C16.4 4 20 7.223 20 11.24C19.9985 12.1928 19.7828 13.1301 19.394 14Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M4 4L20.5 20.5"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
    </svg>
  );
}

ChatOffline.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

ChatOffline.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
