/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Chat(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M14.812 15L12.9 17.55C12.45 18.15 11.55 18.15 11.1 17.55L9.188 15M15 15H18C19.657 15 21 13.657 21 12V6C21 4.343 19.657 3 18 3H6C4.343 3 3 4.343 3 6V12C3 13.657 4.343 15 6 15H9H15Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M7 21H17"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Chat.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Chat.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
