/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Css3(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M6.38438 5H20L17.5844 17.0719L10.3125 19.4875L4 17.0719L4.64062 13.8438H7.31562L7.05312 15.1812L10.8938 16.6375L15.2875 15.1812L15.8969 12.0969H4.95938L5.48438 9.42188H16.4219L16.7719 7.70625H5.83125L6.38438 5Z"
        fill={color}
      />
    </svg>
  );
}

Css3.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Css3.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
