/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Cursor(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M6.731 4.675C9.165 1.541 13.112 1.541 15.546 4.675M12.671 11.583V7.152C12.671 6.336 12.01 5.675 11.194 5.675C10.378 5.675 9.717 6.336 9.717 7.152V10.598V15.675L7.071 14.317C6.469 14.008 5.736 14.123 5.258 14.601C4.625 15.234 4.655 16.269 5.323 16.865L10.148 21.168C10.514 21.495 10.988 21.675 11.479 21.675H16.112C17.049 21.675 17.861 21.024 18.064 20.109L19.137 15.279C19.45 13.869 18.507 12.487 17.08 12.266L12.671 11.583V11.583Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Cursor.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

Cursor.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
