/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function DoubleCheck(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M16.7803 8.28033C17.0732 7.98744 17.0732 7.51256 16.7803 7.21967C16.4874 6.92678 16.0126 6.92678 15.7197 7.21967L10.5854 12.354L11.646 13.4146L16.7803 8.28033ZM8.82321 16.2374L7.76255 15.1768L7.75 15.1893L4.28033 11.7197C3.98744 11.4268 3.51256 11.4268 3.21967 11.7197C2.92678 12.0126 2.92678 12.4874 3.21967 12.7803L7.21967 16.7803C7.51256 17.0732 7.98744 17.0732 8.28033 16.7803L8.82321 16.2374Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M20.25 7.75L11.75 16.25L7.75 12.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

DoubleCheck.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

DoubleCheck.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
