/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Draft = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M21 10.713V18.989C21 20.1 20.129 21 19.054 21H4.946C3.871 21 3 20.1 3 18.99V7.01C3 5.9 3.871 5 4.946 5H10.297"
      stroke={color}
      strokeWidth="1.484"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M19.43 7L17 4.57M18.062 3.505C18.734 2.833 19.824 2.832 20.496 3.505C21.168 4.177 21.168 5.267 20.495 5.939L14.721 11.708C14.534 11.895 14.28 12 14.015 12H12V9.985C12 9.72 12.105 9.466 12.293 9.278L18.062 3.505V3.505ZM8 12H6H8ZM6 16H18H6Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Draft.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Draft.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
