/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function EditIcon(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M21 12V16C21 17.3261 20.4732 18.5979 19.5355 19.5355C18.5979 20.4732 17.3261 21 16 21H8C6.67392 21 5.40215 20.4732 4.46447 19.5355C3.52678 18.5979 3 17.3261 3 16V8C3 6.67392 3.52678 5.40215 4.46447 4.46447C5.40215 3.52678 6.67392 3 8 3H12"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M19 8L16 5"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8 17H16"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M17.3796 3.62044L11.7948 9.20544C11.4888 9.51146 11.2903 9.90848 11.2291 10.3369L11.0104 11.8679C10.9889 12.0187 11.0024 12.1725 11.0499 12.3173C11.0974 12.462 11.1776 12.5939 11.2843 12.7027C11.391 12.8114 11.5214 12.8941 11.6652 12.9444C11.8091 12.9946 11.9625 13.011 12.1138 12.9923L13.5916 12.8098C14.0339 12.7552 14.4453 12.5544 14.7604 12.2393L20.3785 6.62276C20.5755 6.4258 20.7318 6.19196 20.8384 5.9346C20.9451 5.67724 21 5.40139 21 5.1228C21 4.84422 20.9452 4.56837 20.8386 4.31099C20.732 4.05361 20.5757 3.81975 20.3787 3.62276L20.3764 3.62044C20.1796 3.42366 19.946 3.26756 19.6889 3.16107C19.4318 3.05457 19.1563 2.99976 18.878 2.99976C18.5997 2.99976 18.3242 3.05457 18.0671 3.16107C17.81 3.26756 17.5764 3.42366 17.3796 3.62044Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

EditIcon.defaultProps = {
  color: "currentColor",
  size: 24,
};

EditIcon.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
