/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const FileDownload = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <rect
      x="4.75"
      y="2.75"
      width="14.5"
      height="18.5"
      rx="3.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <path
      d="M15 13.7888L12 17L9 13.7888M12.01 9V16.9734V9Z"
      stroke={color}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <rect
      x="14.75"
      y="2.75"
      width="4.5"
      height="5.5"
      rx="1.25"
      fill={color}
      stroke={color}
      strokeWidth={strokeWidth}
    />
  </svg>
);

FileDownload.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

FileDownload.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
