/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const File = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <rect
      x="4.75"
      y="2.75"
      width="14.5"
      height="18.5"
      rx="3.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <rect
      x="14.75"
      y="2.75"
      width="4.5"
      height="5.5"
      rx="1.25"
      fill={color}
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <line
      x1="7.75"
      y1="11.25"
      x2="14.25"
      y2="11.25"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="7.75"
      y1="14.25"
      x2="12.25"
      y2="14.25"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
    <line
      x1="7.75"
      y1="17.25"
      x2="14.25"
      y2="17.25"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
    />
  </svg>
);

File.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

File.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
