/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Form = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M18.8131 21.163H5.18689C4.80753 21.163 4.5 20.8555 4.5 20.4762V6.56446C4.5 6.38635 4.56918 6.2152 4.69296 6.08712L8.19858 2.45956C8.32801 2.32563 8.50627 2.25 8.69252 2.25H18.8131C19.1925 2.25 19.5 2.55753 19.5 2.93689V20.4762C19.5 20.8555 19.1925 21.163 18.8131 21.163ZM18.8131 0.75C20.0209 0.75 21 1.7291 21 2.93689V20.4762C21 21.6839 20.0209 22.663 18.8131 22.663H5.18689C3.9791 22.663 3 21.6839 3 20.4762V6.56446C3 5.9974 3.22026 5.45251 3.61432 5.04474L7.11995 1.41718C7.53201 0.990788 8.09956 0.75 8.69252 0.75H18.8131Z"
      fill={color}
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M7.5 10.9565C7.5 10.5423 7.83579 10.2065 8.25 10.2065H15.75C16.1642 10.2065 16.5 10.5423 16.5 10.9565C16.5 11.3707 16.1642 11.7065 15.75 11.7065H8.25C7.83579 11.7065 7.5 11.3707 7.5 10.9565Z"
      fill={color}
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M7.5 14.087C7.5 13.6727 7.83579 13.337 8.25 13.337H15.75C16.1642 13.337 16.5 13.6727 16.5 14.087C16.5 14.5012 16.1642 14.837 15.75 14.837H8.25C7.83579 14.837 7.5 14.5012 7.5 14.087Z"
      fill={color}
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M7.5 17.2174C7.5 16.8032 7.83579 16.4674 8.25 16.4674H15.75C16.1642 16.4674 16.5 16.8032 16.5 17.2174C16.5 17.6316 16.1642 17.9674 15.75 17.9674H8.25C7.83579 17.9674 7.5 17.6316 7.5 17.2174Z"
      fill={color}
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M9 7.5C9 7.91421 8.66421 8.25 8.25 8.25C7.83579 8.25 7.5 7.91421 7.5 7.5C7.5 7.08579 7.83579 6.75 8.25 6.75C8.66421 6.75 9 7.08579 9 7.5Z"
      fill={color}
    />
    <path
      d="M11.25 7.5C11.25 7.91421 10.9142 8.25 10.5 8.25C10.0858 8.25 9.75 7.91421 9.75 7.5C9.75 7.08579 10.0858 6.75 10.5 6.75C10.9142 6.75 11.25 7.08579 11.25 7.5Z"
      fill={color}
    />
    <path
      d="M13.5 7.5C13.5 7.91421 13.1642 8.25 12.75 8.25C12.3358 8.25 12 7.91421 12 7.5C12 7.08579 12.3358 6.75 12.75 6.75C13.1642 6.75 13.5 7.08579 13.5 7.5Z"
      fill={color}
    />
  </svg>
);

Form.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Form.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
