/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function FullScreen(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0)">
        <path
          d="M14.7705 4.46276L19.6971 4.46385L19.6982 9.39046"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M9.39072 18.5368L4.46411 18.5362L4.46253 13.6096"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M19.6982 13.6095L19.6971 18.5361L14.7705 18.5372"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M4.46301 9.39069L4.46362 4.46409L9.39022 4.46251"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <rect x="8.64999" y="8.65" width="7.6" height="5.7" fill={color} />
      </g>
      <defs>
        <clipPath id="clip0">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
}

FullScreen.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

FullScreen.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
