/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const HamburgerMenu = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <line
      x1="3"
      y1="7.25"
      x2="21"
      y2="7.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <line
      x1="3"
      y1="11.25"
      x2="15"
      y2="11.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <line
      x1="3"
      y1="15.25"
      x2="11"
      y2="15.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
  </svg>
);

HamburgerMenu.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

HamburgerMenu.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
