/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Highlight(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M10.523 20H6V15.477C6 15.0134 6.18428 14.5684 6.51226 14.2407L17.5294 4.00237C18.211 3.31947 19.3171 3.31841 20 4L20.0024 4.00237L21.5 5.527C22.1829 6.20859 22.184 7.31473 21.5024 7.99763L21.5 8L11.759 19.488C11.431 19.8156 10.9865 19.9997 10.523 20Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M2 20H3"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M9 12L13.5 16.5"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Highlight.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

Highlight.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
