/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function History(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_3261_3774)">
        <path
          d="M7.32053 17.6341C8.6935 19.0182 10.5246 19.8532 12.4698 19.9824C14.4151 20.1116 16.3405 19.5261 17.8845 18.3358C19.4284 17.1455 20.4846 15.4324 20.8546 13.5183C21.2246 11.6042 20.8829 9.62091 19.8938 7.94097C18.9047 6.26103 17.3361 5.00009 15.4829 4.39505C13.6296 3.79 11.6192 3.88249 9.82937 4.65514C8.03951 5.42779 6.59338 6.82742 5.76266 8.59108C4.93194 10.3547 4.77382 12.3611 5.31799 14.2331"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M7.50138 12.0678L4.99066 14.5577L2.50076 12.047"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12.5 8V12.5L15.5 15"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_3261_3774">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
}

History.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

History.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
