/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const HourGlass = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 32 32" fill="none" {...other}>
    <path d="M15 19H17V21H15V19ZM15 23H17V25H15V23Z" fill={color} />
    <path
      d="M23 11.67V4H26V2H6V4H9V11.67C9 12.1027 9.14036 12.5238 9.4 12.87L11.75 16L9.4 19.13C9.14036 19.4762 9 19.8973 9 20.33V28H6V30H26V28H23V20.33C23 19.8973 22.8596 19.4762 22.6 19.13L20.25 16L22.6 12.87C22.8596 12.5238 23 12.1027 23 11.67ZM21 4V11H11V4H21ZM21 20.33V28H11V20.33L14.25 16L12 13H20L17.75 16L21 20.33Z"
      fill={color}
    />
  </svg>
);

HourGlass.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

HourGlass.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
