/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Image(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0)">
        <path
          d="M21 16.014L16.707 11.721C16.316 11.33 15.683 11.33 15.293 11.721L11 16.014"
          stroke={color}
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M18 21.014H6C4.343 21.014 3 19.671 3 18.014V6.014C3 4.357 4.343 3.014 6 3.014H18C19.657 3.014 21 4.357 21 6.014V18.014C21 19.671 19.657 21.014 18 21.014Z"
          stroke={color}
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M15.9998 21.014L9.7068 14.721C9.3158 14.33 8.6828 14.33 8.2928 14.721L3.4458 19.568M9.26497 8.74883C9.41142 8.89527 9.41142 9.13271 9.26497 9.27916C9.11852 9.4256 8.88109 9.4256 8.73464 9.27916C8.58819 9.13271 8.58819 8.89527 8.73464 8.74883C8.88109 8.60238 9.11852 8.60238 9.26497 8.74883Z"
          stroke={color}
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
}

Image.defaultProps = {
  color: "currentColor",
  size: 24,
};

Image.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
