/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Inbox(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M17 17H6.99999M12 3V11M12 11L15 8M12 11L8.99999 8M21 12V17C21 19.2 19.2 21 17 21H6.99999L6.98999 20.999C4.77999 20.989 2.98999 19.199 2.98999 16.989V11.989"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Inbox.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Inbox.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
