/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IndeterminateCircle(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <circle
        cx="12"
        cy="12"
        r="8.25"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <line
        x1="8.75"
        y1="12.25"
        x2="15.25"
        y2="12.25"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
    </svg>
  );
}

IndeterminateCircle.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

IndeterminateCircle.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
