/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Input(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_861:2155)">
        <path
          d="M5 4H6C7.105 4 8 4.895 8 6C8 4.895 8.895 4 10 4H11M20 16H4C3.448 16 3 15.552 3 15V9C3 8.448 3.448 8 4 8H20C20.552 8 21 8.448 21 9V15C21 15.552 20.552 16 20 16ZM11 20H10C8.895 20 8 19.105 8 18C8 19.105 7.105 20 6 20H5H11ZM8 6V18V6Z"
          stroke={color}
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_861:2155">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
}

Input.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Input.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
