/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Link(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M17.7166 12.3594L19.4466 10.6294C21.1392 8.9873 21.1801 6.284 19.538 4.59141C17.8959 2.89882 15.1926 2.85789 13.5 4.5C13.4691 4.53001 13.4386 4.56048 13.4086 4.59141L10.0109 7.951C8.34355 9.61717 8.3426 12.3195 10.0088 13.9869L10.0109 13.989L9.9999 14C10.3445 14.3381 10.7447 14.6144 11.1829 14.817"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12.806 9.193C13.2443 9.39593 13.6445 9.67262 13.989 10.011C15.6564 11.6772 15.6573 14.3795 13.9912 16.0469L13.989 16.049L10.8082 19.268C9.11565 20.9101 6.41235 20.8692 4.77024 19.1766C3.16318 17.5201 3.16318 14.8865 4.77024 13.23L6.50024 11.5"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Link.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

Link.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
