/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function List(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M20 5H4C3.44772 5 3 5.44772 3 6V9C3 9.55228 3.44772 10 4 10H20C20.5523 10 21 9.55228 21 9V6C21 5.44772 20.5523 5 20 5Z"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <path
        d="M20 13H4C3.44772 13 3 13.4477 3 14V17C3 17.5523 3.44772 18 4 18H20C20.5523 18 21 17.5523 21 17V14C21 13.4477 20.5523 13 20 13Z"
        stroke={color}
        strokeWidth={strokeWidth}
      />
    </svg>
  );
}

List.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

List.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
