/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Lock(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <circle
        cx="12"
        cy="15"
        r="5.25"
        stroke={color}
        strokeWidth={strokeWidth}
      />
      <path
        d="M14.25 9.43614V6.75C14.25 5.50736 13.2426 4.5 12 4.5C10.7574 4.5 9.75 5.50736 9.75 6.75V9.43614C9.20575 9.65644 8.70119 9.95429 8.25 10.316V6.75C8.25 4.67893 9.92893 3 12 3C14.0711 3 15.75 4.67893 15.75 6.75V10.316C15.2988 9.95429 14.7942 9.65644 14.25 9.43614Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <circle cx="12" cy="15" r="1.5" fill={color} />
    </svg>
  );
}

Lock.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Lock.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
