/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function MailSend(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M6.9349 17.955H19.5938C20.37 17.955 21 17.3258 21 16.5488V7.40703C21 6.63002 20.37 6 19.593 6H6.9349C6.15876 6 5.5 6.63002 5.5 7.40703"
        stroke={color}
        strokeWidth="1.28927"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M5.5 7.455L12.2441 11.6152C12.8415 12.0424 13.6442 12.0433 14.2425 11.6169L20.5 7.455"
        stroke={color}
        strokeWidth="1.28927"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line
        x1="3.75"
        y1="12.205"
        x2="7.25"
        y2="12.205"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
      <line
        x1="3.75"
        y1="15.205"
        x2="9.25"
        y2="15.205"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
      />
    </svg>
  );
}

MailSend.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MailSend.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
