/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Matrix = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <rect
      x="3.75"
      y="4.75"
      width="16.5"
      height="14.5"
      rx="2.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <path d="M3 7C3 5.34315 4.34315 4 6 4H12V12H3V7Z" fill={color} />
    <path d="M12 12H21V17C21 18.6569 19.6569 20 18 20H12V12Z" fill={color} />
  </svg>
);

Matrix.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Matrix.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
