/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function MatrixDots(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <circle cx="5.5" cy="5.5" r="2.5" fill={color} />
      <circle cx="12" cy="5.5" r="2.5" fill={color} />
      <circle cx="18.5" cy="5.5" r="2.5" fill={color} />
      <circle cx="5.5" cy="12" r="2" stroke={color} />
      <circle cx="12" cy="12" r="2.5" fill={color} />
      <circle cx="18.5" cy="12" r="2" stroke={color} />
      <circle cx="5.5" cy="18.5" r="2" stroke={color} />
      <circle cx="12" cy="18.5" r="2" stroke={color} />
      <circle cx="18.5" cy="18.5" r="2" stroke={color} />
    </svg>
  );
}

MatrixDots.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MatrixDots.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
