/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function MenuLayout(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <mask id="path-1-inside-1_1254:2977" fill={color}>
        <rect x="4" y="4" width="6" height="6" rx="1" />
      </mask>
      <rect
        x="4"
        y="4"
        width="6"
        height="6"
        rx="1"
        stroke={color}
        mask="url(#path-1-inside-1_1254:2977)"
        strokeWidth="3"
      />
      <mask id="path-2-inside-2_1254:2977" fill={color}>
        <rect x="4" y="14" width="6" height="6" rx="1" />
      </mask>
      <rect
        x="4"
        y="14"
        width="6"
        height="6"
        rx="1"
        stroke={color}
        mask="url(#path-2-inside-2_1254:2977)"
        strokeWidth="3"
      />
      <mask id="path-3-inside-3_1254:2977" fill={color}>
        <rect x="14" y="4" width="6" height="6" rx="1" />
      </mask>
      <rect
        x="14"
        y="4"
        width="6"
        height="6"
        rx="1"
        stroke={color}
        mask="url(#path-3-inside-3_1254:2977)"
        strokeWidth="3"
      />
      <mask id="path-4-inside-4_1254:2977" fill={color}>
        <rect x="14" y="14" width="6" height="6" rx="1" />
      </mask>
      <rect
        x="14"
        y="14"
        width="6"
        height="6"
        rx="1"
        stroke={color}
        mask="url(#path-4-inside-4_1254:2977)"
        strokeWidth="3"
      />
    </svg>
  );
}

MenuLayout.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MenuLayout.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
