/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function MenuVertical(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M11.997 17.5C11.722 17.5 11.497 17.725 11.5 18C11.5 18.275 11.725 18.5 12 18.5C12.275 18.5 12.5 18.275 12.5 18C12.5 17.725 12.275 17.5 11.997 17.5Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.997 11.5C11.722 11.5 11.497 11.725 11.5 12C11.5 12.275 11.725 12.5 12 12.5C12.275 12.5 12.5 12.275 12.5 12C12.5 11.725 12.275 11.5 11.997 11.5Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.997 5.5C11.722 5.5 11.497 5.725 11.5 6C11.5 6.275 11.725 6.5 12 6.5C12.275 6.5 12.5 6.275 12.5 6C12.5 5.725 12.275 5.5 11.997 5.5Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

MenuVertical.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MenuVertical.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
