/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function MenuLayout(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_3134_3541)">
        <rect
          x="4"
          y="4"
          width="6"
          height="6"
          rx="1"
          stroke={color}
          strokeWidth={strokeWidth}
        />
        <rect
          x="4"
          y="14"
          width="6"
          height="6"
          rx="1"
          stroke={color}
          strokeWidth={strokeWidth}
        />
        <rect
          x="14"
          y="4"
          width="6"
          height="6"
          rx="1"
          stroke={color}
          strokeWidth={strokeWidth}
        />
        <rect
          x="14"
          y="14"
          width="6"
          height="6"
          rx="1"
          stroke={color}
          strokeWidth={strokeWidth}
        />
      </g>
      <defs>
        <clipPath id="clip0_3134_3541">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
}

MenuLayout.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MenuLayout.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
