/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Merge(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M17 8L21 12M21 12L17 16M21 12H15.606M15.606 12C14.4968 12.0001 13.4048 11.7263 12.4268 11.2029C11.4489 10.6796 10.6153 9.9229 10 9C9.38474 8.0771 8.55113 7.3204 7.57318 6.79705C6.59522 6.27371 5.50318 5.99992 4.394 6L3 6M15.606 12C14.4968 11.9999 13.4048 12.2737 12.4268 12.7971C11.4489 13.3204 10.6153 14.0771 10 15C9.38474 15.9229 8.55113 16.6796 7.57318 17.2029C6.59522 17.7263 5.50318 18.0001 4.394 18H3"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Merge.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Merge.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
