/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Movie = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <rect
      x="3.75"
      y="5.75"
      width="16.5"
      height="12.5"
      rx="1.25"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <path d="M10 14.5L14 12L10 9.5" fill={color} />
    <path
      d="M10 14.5L14 12L10 9.5V14.5Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Movie.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Movie.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
