/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const MultipleChoice = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M12 5H20"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12 12H20"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M12 19H20"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <rect
      x="3.75"
      y="2.25"
      width="4.5"
      height="4.5"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <rect
      x="3.75"
      y="9.75"
      width="4.5"
      height="4.5"
      stroke={color}
      strokeWidth={strokeWidth}
    />
    <rect
      x="3.75"
      y="17.25"
      width="4.5"
      height="4.5"
      stroke={color}
      strokeWidth={strokeWidth}
    />
  </svg>
);

MultipleChoice.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

MultipleChoice.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
