/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoInterview = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M9.61801 3H14.382V3C14.9343 3 15.382 3.44772 15.382 4.00001C15.382 4.15525 15.3459 4.30836 15.2764 4.44721L14 7H10L8.72362 4.44721V4.44721C8.47663 3.95323 8.67686 3.35256 9.17084 3.10557C9.30968 3.03615 9.46278 3.00001 9.61801 3V3Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M9.99969 6.99769L8.0144 18.581V18.581C7.95102 18.9508 8.09994 19.325 8.40009 19.5501L11.3999 21.8V21.8C11.7555 22.0667 12.2445 22.0667 12.6001 21.8L15.5999 19.5501V19.5501C15.9001 19.325 16.049 18.9508 15.9856 18.5811L14.0003 6.99765"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

NeetoInterview.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

NeetoInterview.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
