/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function PlusSolid(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M4 6C4 4.89543 4.89543 4 6 4H18C19.1046 4 20 4.89543 20 6V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V6Z"
        fill={color}
      />
      <path
        d="M12.8333 6.75C12.8333 6.33579 12.4975 6 12.0833 6C11.6691 6 11.3333 6.33579 11.3333 6.75V11.3333H6.75C6.33579 11.3333 6 11.6691 6 12.0833C6 12.4975 6.33579 12.8333 6.75 12.8333H11.3333V17.4167C11.3333 17.8309 11.6691 18.1667 12.0833 18.1667C12.4975 18.1667 12.8333 17.8309 12.8333 17.4167V12.8333H17.4167C17.8309 12.8333 18.1667 12.4975 18.1667 12.0833C18.1667 11.6691 17.8309 11.3333 17.4167 11.3333H12.8333V6.75Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </svg>
  );
}

PlusSolid.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

PlusSolid.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
