/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Pointer(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M15.388 13.498L17.94 20.512L13.242 22.222L10.689 15.208L6.79 17.653L8.41 1.633L19.947 12.865L15.389 13.498H15.388ZM15.377 19.316L12.662 11.856L15.622 11.446L9.982 5.956L9.192 13.786L11.722 12.199L14.437 19.659L15.377 19.316V19.316Z"
        fill={color}
      />
    </svg>
  );
}

Pointer.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Pointer.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
