/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function PrintIcon(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M16.814 8V4C16.814 3.448 16.366 3 15.814 3H8.18604C7.63404 3 7.18604 3.448 7.18604 4V8"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M7 17H4C3.448 17 3 16.552 3 16V9C3 8.448 3.448 8 4 8H20C20.552 8 21 8.448 21 9V16C21 16.552 20.552 17 20 17H17"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M16 21H8C7.448 21 7 20.552 7 20V14H17V20C17 20.552 16.552 21 16 21Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

PrintIcon.defaultProps = {
  color: "currentColor",
  size: 24,
};

PrintIcon.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
