/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Radio(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 16 16" fill="none" height={size} width={size} {...other}>
      <circle cx="8" cy="8" r="5.25" stroke={color} strokeWidth={strokeWidth} />
      <circle cx="8" cy="8" r="2" fill={color} />
    </svg>
  );
}

Radio.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

Radio.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
