/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Radio = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <circle cx="12" cy="12" r="8.25" stroke={color} strokeWidth={strokeWidth} />
    <circle cx="12" cy="12" r="3" fill={color} />
  </svg>
);

Radio.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Radio.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
