/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Redirection(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 32 32" fill="none" height={size} width={size} {...other}>
      <path
        d="M17.2946 26.6047C15.8986 26.7745 14.4829 26.6677 13.1282 26.2903C11.7736 25.9129 10.5065 25.2724 9.39933 24.4054C8.29219 23.5383 7.36666 22.4617 6.6756 21.2369C5.98454 20.0122 5.54148 18.6633 5.37171 17.2674C5.02885 14.4481 5.81998 11.6081 7.57108 9.37209C9.32218 7.13611 11.8898 5.68733 14.7091 5.34446M13.1734 11.0756L14.8989 4.63612L8.45938 2.91066M22.5355 24.4063L22.539 24.3934M20.0298 6.09376L20.0332 6.08088M24.4335 9.44092L24.437 9.42804M26.5635 14.5254L26.5669 14.5126M25.8827 20.0025L25.8861 19.9897"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Redirection.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Redirection.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
