/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Report(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M9.167 20.5H4.444C3.922 20.5 3.5 20.077 3.5 19.556V15.778C3.5 15.256 3.923 14.834 4.444 14.834H9.166L9.167 20.5ZM14.833 4.444V20.5H19.555C20.077 20.5 20.499 20.077 20.499 19.556V4.444C20.499 3.922 20.076 3.5 19.555 3.5H15.777C15.256 3.5 14.833 3.923 14.833 4.444Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M14.833 20.5H9.166V10.111C9.166 9.589 9.589 9.167 10.11 9.167H14.832"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Report.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "2",
};

Report.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
