/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function RightAlign(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 18 19" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_1047_4040)">
        <rect
          x="4.5"
          y="11.333"
          width="11.5714"
          height="3.85714"
          rx="1"
          fill={color}
        />
        <mask id="path-2-inside-1_1047_4040" fill={color}>
          <rect x="4.5" y="6.19043" width="9" height="3.85714" rx="1" />
        </mask>
        <rect
          x="4.5"
          y="6.19043"
          width="9"
          height="3.85714"
          rx="1"
          stroke={color}
          mask="url(#path-2-inside-1_1047_4040)"
          strokeWidth="3"
        />
        <line
          x1="2.25"
          y1="2.97607"
          x2="2.25"
          y2="17.1189"
          stroke={color}
          strokeWidth={strokeWidth}
        />
      </g>
      <defs>
        <clipPath id="clip0_1047_4040">
          <rect
            width="18"
            height="18"
            fill={color}
            transform="translate(0 0.619141)"
          />
        </clipPath>
      </defs>
    </svg>
  );
}

RightAlign.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

RightAlign.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
