/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Security = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 32 32" fill="none" {...other}>
    <path
      d="M18.0349 14.8343V13.037C18.0349 11.913 17.1229 11.001 15.9989 11.001V11.001C14.8749 11.001 13.9629 11.913 13.9629 13.037V14.8343"
      stroke={color}
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M18.332 14.8359H13.6654C12.9294 14.8359 12.332 15.4333 12.332 16.1693V19.0013C12.332 19.7373 12.9294 20.3346 13.6654 20.3346H18.332C19.068 20.3346 19.6654 19.7373 19.6654 19.0013V16.1693C19.6654 15.4333 19.068 14.8359 18.332 14.8359Z"
      stroke={color}
      fillRule="evenodd"
      clipRule="evenodd"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M26.6654 14.99C26.6654 20.814 22.456 26.2726 16.692 27.9046C16.2414 28.0326 15.756 28.0326 15.3054 27.9046C9.54136 26.274 5.33203 20.814 5.33203 14.99V9.61931C5.33203 8.53664 5.9867 7.56064 6.98936 7.15131L13.4747 4.49798C15.0934 3.83531 16.9067 3.83531 18.524 4.49798L25.0094 7.15131C26.0107 7.56064 26.6654 8.53664 26.6654 9.61931V14.99Z"
      stroke={color}
      fillRule="evenodd"
      clipRule="evenodd"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Security.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Security.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
