/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Send(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 16 16" fill="none" height={size} width={size} {...other}>
      <path
        d="M14.6654 1.3335L9.9987 14.6668L7.33203 8.66683L1.33203 6.00016L14.6654 1.3335Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Send.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Send.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
