/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Suitcase = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M19 21H5V21C3.89543 21 3 20.1046 3 19V10V10C3 8.89543 3.89543 8 5 8H19V8C20.1046 8 21 8.89543 21 10V19V19C21 20.1046 20.1046 21 19 21C19 21 19 21 19 21V21Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M16 21V6C16 4.89543 15.1046 4 14 4H10V4C8.89543 4 8 4.89543 8 6V6V21"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

Suitcase.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Suitcase.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
