/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Swap(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M3 8.27273L6.27273 5L9.54545 8.27273"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.1818 19.7273H9.54543C8.67745 19.7273 7.84502 19.3825 7.23126 18.7687C6.61751 18.155 6.27271 17.3225 6.27271 16.4546L6.27271 5.00002"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M21 16.4546L17.7273 19.7273L14.4546 16.4546"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12.8182 5.00002H14.4546C15.3226 5.00002 16.155 5.34482 16.7688 5.95858C17.3825 6.57234 17.7273 7.40477 17.7273 8.27275V19.7273"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Swap.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Swap.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
