/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Tags(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M14.8344 10.1456C14.6911 10.2889 14.6911 10.5213 14.8344 10.6646C14.9778 10.8079 15.2101 10.8079 15.3534 10.6646C15.4968 10.5213 15.4968 10.2889 15.3534 10.1456C15.2101 10.0023 14.9778 10.0023 14.8344 10.1456Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M4.5 10L11.006 3.577C11.381 3.207 11.885 3 12.411 3H16.5M12.29 6.29L5.08 13.5C4.308 14.272 4.308 15.524 5.08 16.296L9.204 20.42C9.976 21.192 11.228 21.192 12 20.42L19.21 13.21C19.395 13.025 19.5 12.773 19.5 12.511V6.989C19.5 6.443 19.057 6 18.511 6H12.988C12.726 6 12.475 6.104 12.29 6.29V6.29Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Tags.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

Tags.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
