/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function TextBold(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M7 6H12.875C13.6706 6 14.4337 6.31607 14.9963 6.87868C15.5589 7.44129 15.875 8.20435 15.875 9V9C15.875 9.79565 15.5589 10.5587 14.9963 11.1213C14.4337 11.6839 13.6706 12 12.875 12H7V6ZM7 12H14C14.7956 12 15.5587 12.3161 16.1213 12.8787C16.6839 13.4413 17 14.2044 17 15V15C17 15.7956 16.6839 16.5587 16.1213 17.1213C15.5587 17.6839 14.7956 18 14 18H7V12Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

TextBold.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

TextBold.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
