/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function TimeTracking(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M14 20.274C18.8467 19.1713 21.8818 14.3484 20.7791 9.5017C19.6764 4.65499 14.8535 1.61987 10.0068 2.72257C5.16012 3.82526 2.125 8.64821 3.2277 13.4949C3.38566 14.1892 3.62545 14.8622 3.94204 15.5"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.786 8.463V11.979L14.55 13.665"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M10 19.5H5M7.5 22V17"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

TimeTracking.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

TimeTracking.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
