/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function TimeTracking(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 25 25" fill="none" height={size} width={size} {...other}>
      <path
        d="M14.0312 20.9695C12.2732 21.3725 10.3803 21.2595 8.58825 20.5165C3.99725 18.6145 1.81725 13.3515 3.71825 8.76053C5.61925 4.16953 10.8832 1.98953 15.4742 3.89053C19.5903 5.59553 21.7583 10.0015 20.7943 14.2035M17.2812 19.4545H21.2812M19.2812 21.4545V17.4545"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M11.7493 8.18953V12.8405L15.4052 15.0695"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

TimeTracking.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

TimeTracking.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
