/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function UserAdd(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M12.5 15H8C6.93913 15 5.92172 15.4214 5.17157 16.1716C4.42143 16.9217 4 17.9391 4 19V21"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12 11C14.2091 11 16 9.20914 16 7C16 4.79086 14.2091 3 12 3C9.79086 3 8 4.79086 8 7C8 9.20914 9.79086 11 12 11Z"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M19.3742 12.15C19.3742 11.7358 19.0384 11.4 18.6242 11.4C18.21 11.4 17.8742 11.7358 17.8742 12.15V14.2742H15.75C15.3358 14.2742 15 14.61 15 15.0242C15 15.4384 15.3358 15.7742 15.75 15.7742H17.8742V17.8983C17.8742 18.3126 18.21 18.6483 18.6242 18.6483C19.0384 18.6483 19.3742 18.3126 19.3742 17.8983V15.7742H21.4983C21.9126 15.7742 22.2483 15.4384 22.2483 15.0242C22.2483 14.61 21.9126 14.2742 21.4983 14.2742H19.3742V12.15Z"
        fill={color}
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </svg>
  );
}

UserAdd.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

UserAdd.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
