/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function VideoIcon(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M19.4751 16.0531L16.0498 13.9417V10.0583L19.4751 7.94689C19.6266 7.8535 19.8003 7.80223 19.9782 7.79839C20.1561 7.79455 20.3319 7.83826 20.4873 7.92502C20.6427 8.01178 20.7721 8.13845 20.8622 8.29194C20.9523 8.44543 20.9998 8.62018 20.9998 8.79816V15.2018C20.9998 15.3798 20.9523 15.5546 20.8622 15.708C20.7721 15.8615 20.6427 15.9882 20.4873 16.075C20.3319 16.1617 20.1561 16.2054 19.9782 16.2016C19.8003 16.1977 19.6266 16.1465 19.4751 16.0531Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M13.05 6H6C4.34315 6 3 7.34315 3 9V15C3 16.6569 4.34315 18 6 18H13.05C14.7069 18 16.05 16.6569 16.05 15V9C16.05 7.34315 14.7069 6 13.05 6Z"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

VideoIcon.defaultProps = {
  color: "currentColor",
  size: 24,
};

VideoIcon.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
