/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function View(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M2.08984 13.09C7.56284 6.043 16.4358 6.043 21.9088 13.09"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M15.431 9.31802C17.1884 11.0754 17.1884 13.9246 15.431 15.682C13.6736 17.4393 10.8244 17.4393 9.06704 15.682C7.30968 13.9246 7.30968 11.0754 9.06704 9.31802C10.8244 7.56066 13.6736 7.56066 15.431 9.31802"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

View.defaultProps = {
  color: "currentColor",
  size: 24,
};

View.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
