/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const VolumeOutline = ({ size, color, strokeWidth, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" {...other}>
    <path
      d="M15.537 15.978C16.699 15.256 17.5 13.754 17.5 12.005C17.5 10.256 16.699 8.753 15.537 8.022M18.505 19.065C20.313 17.51 21.5 14.93 21.5 12.003C21.5 9.072 20.311 6.49 18.5 4.936M5.875 8.625H3.5C2.948 8.625 2.5 9.073 2.5 9.625V14.375C2.5 14.927 2.948 15.375 3.5 15.375H5.875L9.854 18.746C10.504 19.297 11.5 18.835 11.5 17.983V6.017C11.5 5.165 10.503 4.703 9.854 5.254L5.875 8.625Z"
      stroke={color}
      strokeWidth={strokeWidth}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

VolumeOutline.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

VolumeOutline.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
