/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function VolumeOutline0(props) {
  const { size, color, strokeWidth, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M5.875 8.6251L9.854 5.2541C10.504 4.7031 11.5 5.1651 11.5 6.0171V17.9821C11.5 18.8341 10.503 19.2961 9.854 18.7451L5.875 15.3741"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M5.875 15.375H3.5C2.948 15.375 2.5 14.927 2.5 14.375V9.625C2.5 9.073 2.948 8.625 3.5 8.625H5.875M20.58 9.69L16.08 14.19M20.58 14.19L16.08 9.69"
        stroke={color}
        strokeWidth={strokeWidth}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

VolumeOutline0.defaultProps = {
  color: "currentColor",
  size: 24,
  strokeWidth: "1.5",
};

VolumeOutline0.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  strokeWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
