/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoSign = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_448)"
    />
    <mask
      id="mask0_3502_448"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_448)"
      />
    </mask>
    <g mask="url(#mask0_3502_448)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430201V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_448)"
      />
    </g>
    <g filter="url(#filter0_d_3502_448)">
      <path
        d="M22.169 25.3499L22.3992 25.3483C23.4395 25.3483 23.9859 25.7795 24.6601 26.8011L24.9958 27.3196C25.2575 27.7071 25.4208 27.8694 25.6266 27.9542C25.9954 28.1062 26.3012 28.0314 27.4239 27.4908L27.7676 27.3235C28.4698 26.9788 28.9489 26.7814 29.4903 26.6461C29.8329 26.5605 30.18 26.7687 30.2657 27.1113C30.3513 27.4539 30.143 27.801 29.8005 27.8866C29.4639 27.9708 29.1415 28.0915 28.7197 28.2859L27.732 28.761C26.3954 29.3922 25.9421 29.4673 25.1393 29.1364C24.6064 28.9168 24.3034 28.5991 23.86 27.9211L23.6941 27.662C23.181 26.8535 22.9227 26.627 22.3992 26.627L22.2639 26.6302C21.8947 26.6526 21.6556 26.8218 20.0628 28.0038C18.5776 29.106 17.4449 29.6325 16.0044 29.6325C14.2484 29.6325 12.5937 29.3098 11.0453 28.6649L13.5025 28.0968C14.3071 28.2681 15.1409 28.3537 16.0044 28.3537C17.1047 28.3537 18.0167 27.9298 19.3008 26.9769L20.2897 26.2473C21.3735 25.4595 21.6146 25.3619 22.169 25.3499ZM27.5373 10.1928C28.964 11.6196 28.964 13.9327 27.5373 15.3595L26.6546 16.2424C27.6366 17.4372 27.6012 18.7034 26.6882 19.6192L24.1298 22.1775C23.88 22.4271 23.4752 22.4269 23.2256 22.1771C22.9761 21.9273 22.9763 21.5224 23.2261 21.2729L25.7827 18.7163C26.1962 18.3016 26.244 17.7867 25.7486 17.1489L16.717 26.1804C16.4628 26.4346 16.1423 26.6123 15.792 26.6931L10.6082 27.8894C10.1478 27.9956 9.73516 27.583 9.8414 27.1226L11.0377 21.9388C11.1185 21.5885 11.2961 21.268 11.5503 21.0138L22.3707 10.1929C23.7973 8.76614 26.1105 8.7661 27.5373 10.1928Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_448"
        x="9.82454"
        y="9.1228"
        width="21.1621"
        height="21.3284"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_448"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_448"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_448"
        x1="-15.876"
        y1="-21.8295"
        x2="54.2818"
        y2="58.3092"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#59CBEF" />
        <stop offset="0.609375" stopColor="#698EEF" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_448"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_448"
        x1="32.2489"
        y1="9.63823"
        x2="0.4302"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoSign.defaultProps = { size: 24 };

NeetoSign.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
