/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoBugtrap = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <rect
      width="40"
      height="40"
      rx="10.7731"
      fill="url(#paint0_linear_3502_449)"
    />
    <mask
      id="mask0_3502_449"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <rect
        width="40"
        height="40"
        rx="10.7731"
        fill="url(#paint1_linear_3502_449)"
      />
    </mask>
    <g mask="url(#mask0_3502_449)">
      <path
        d="M37.4194 22.3657C37.4194 12.1514 29.1391 3.87109 18.9248 3.87109H0.430168V40.8603H37.4194V22.3657Z"
        fill="url(#paint2_linear_3502_449)"
      />
    </g>
    <g filter="url(#filter0_d_3502_449)">
      <path
        d="M30.4576 28.1426L27.6617 25.3801C27.38 25.8328 27.0447 26.2572 26.6572 26.6433C26.2665 27.0344 25.8379 27.3732 25.3801 27.6569L28.1922 30.4352C28.8225 31.0587 29.8363 31.0532 30.4631 30.4274C30.4657 30.4248 30.4679 30.4226 30.4702 30.4206C31.0992 29.7913 31.0908 28.7683 30.4576 28.1426Z"
        fill="white"
      />
      <path
        d="M19.0643 26.7836C23.3405 26.7836 26.7836 23.3409 26.7836 19.1228C26.7836 14.9047 23.3405 11.462 19.0643 11.462C14.7882 11.462 11.345 14.9047 11.345 19.1228C11.345 23.3409 14.7882 26.7836 19.0643 26.7836ZM19.0643 29.1228C24.6195 29.1228 29.1228 24.6457 29.1228 19.1228C29.1228 13.6 24.6195 9.1228 19.0643 9.1228C13.5092 9.1228 9.00587 13.6 9.00587 19.1228C9.00587 24.6457 13.5092 29.1228 19.0643 29.1228Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M15.6287 21.0299C15.6058 20.8673 15.5944 20.7033 15.5946 20.539V20.0482H14.6199V19.0664H15.5946V18.5756C15.5946 18.4087 15.6063 18.2452 15.6287 18.0847H14.6199V17.103H15.923C16.2217 16.4705 16.7045 15.9445 17.307 15.595L16.7953 15.0796L17.4854 14.386L18.3056 15.2126C18.7678 15.1153 19.2449 15.1153 19.7071 15.2126L20.5273 14.386L21.2169 15.0806L20.7052 15.596C21.3074 15.9453 21.79 16.4709 22.0887 17.103H23.3918V18.0847H22.3831C22.4055 18.2452 22.4172 18.4087 22.4172 18.5756V19.0664H23.3918V20.0482H22.4172V20.539C22.4172 20.7059 22.4055 20.8694 22.3831 21.0299H23.3918V22.0117H22.0887C21.8122 22.5995 21.3757 23.0963 20.83 23.4441C20.2843 23.792 19.6517 23.9766 19.0059 23.9766C18.3601 23.9766 17.7275 23.792 17.1818 23.4441C16.636 23.0963 16.1995 22.5995 15.923 22.0117H14.6199V21.0299H15.6287ZM17.5439 18.0847V19.0664H20.4679V18.0847H17.5439ZM17.5439 20.0482V21.0299H20.4679V20.0482H17.5439Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3502_449"
        x="9.00587"
        y="9.1228"
        width="22.6331"
        height="22.5957"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.350877" dy="0.467836" />
        <feGaussianBlur stdDeviation="0.175439" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3502_449"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3502_449"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3502_449"
        x1="-27.5439"
        y1="-30.1754"
        x2="76.7251"
        y2="79.2982"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.176638" stopColor="#8BBAFF" />
        <stop offset="1" stopColor="#753BF1" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3502_449"
        x1="-2.80164"
        y1="-2.27633"
        x2="37.2385"
        y2="61.1108"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3502_449"
        x1="32.2489"
        y1="9.63823"
        x2="0.430167"
        y2="40.8603"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="white" stopOpacity="0.16" />
        <stop offset="0.53125" stopColor="white" stopOpacity="0" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoBugtrap.defaultProps = { size: 24 };

NeetoBugtrap.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
