/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoTestify = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3193_174)"
    />
    <g filter="url(#filter0_d_3193_174)">
      <path
        d="M31.8843 31.144L28.7342 28.0316C28.4167 28.5415 28.039 29.0197 27.6024 29.4548C27.1622 29.8954 26.6793 30.2771 26.1634 30.5968L29.3318 33.7272C30.042 34.4297 31.1843 34.4235 31.8905 33.7184C31.8934 33.7155 31.896 33.7129 31.8985 33.7107C32.6072 33.0017 32.5977 31.8491 31.8843 31.144Z"
        fill="white"
      />
      <path
        d="M19.0473 29.6129C23.8653 29.6129 27.7447 25.734 27.7447 20.9814C27.7447 16.2288 23.8653 12.3499 19.0473 12.3499C14.2293 12.3499 10.3499 16.2288 10.3499 20.9814C10.3499 25.734 14.2293 29.6129 19.0473 29.6129ZM19.0473 32.2485C25.3064 32.2485 30.3803 27.2041 30.3803 20.9814C30.3803 14.7588 25.3064 9.71429 19.0473 9.71429C12.7883 9.71429 7.71431 14.7588 7.71431 20.9814C7.71431 27.2041 12.7883 32.2485 19.0473 32.2485Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M22.7156 17.0706L21.5494 18.2275L23.7089 20.9155L21.5494 23.6068L22.7156 24.7637L25.768 20.9155L22.7156 17.0706ZM16.8086 18.2242L15.6424 17.0681L12.5901 20.9155L15.6424 24.7605L16.8086 23.6036L14.6491 20.9155L16.8086 18.2242ZM17.5318 25.0007H19.179L20.8262 16.8304H19.179L17.5318 25.0007Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3193_174"
        x="7.71431"
        y="9.71429"
        width="26.4247"
        height="26.5364"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3193_174"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3193_174"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3193_174"
        x1="40"
        y1="48.1429"
        x2="-12.4286"
        y2="-17"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FF9E45" />
        <stop offset="1" stopColor="#FFF27A" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoTestify.defaultProps = { size: 24 };

NeetoTestify.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
