/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoInvisible = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3193_167)"
    />
    <g filter="url(#filter0_d_3193_167)">
      <path
        d="M15.6308 11.2547C11.9516 11.2547 8.96899 14.2373 8.96899 17.9165C8.96899 21.5957 11.9516 24.5783 15.6308 24.5783V25.5473C11.4164 25.5473 8 22.1309 8 17.9165C8 13.7021 11.4164 10.2857 15.6308 10.2857C19.8452 10.2857 23.2616 13.7021 23.2616 17.9165H22.2926C22.2926 14.2373 19.31 11.2547 15.6308 11.2547Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M15.6308 14.4039C13.6909 14.4039 12.1182 15.9765 12.1182 17.9165C12.1182 19.8564 13.6909 21.429 15.6308 21.429V22.398C13.1557 22.398 11.1492 20.3916 11.1492 17.9165C11.1492 15.4413 13.1557 13.4349 15.6308 13.4349C18.1059 13.4349 20.1124 15.4413 20.1124 17.9165H19.1434C19.1434 15.9765 17.5708 14.4039 15.6308 14.4039Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M15.4971 18.4121C15.4094 18.1709 15.6432 17.9371 15.8843 18.0248L31.644 23.7562C31.9101 23.853 31.9089 24.2298 31.6421 24.3248L24.4399 26.8893C24.3536 26.92 24.2859 26.9882 24.2558 27.0748L21.7944 34.1581C21.7011 34.4267 21.3222 34.4294 21.225 34.1621L15.4971 18.4121Z"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3193_167"
        x="8"
        y="10.2857"
        width="25.5572"
        height="26.0753"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3193_167"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3193_167"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3193_167"
        x1="43.1429"
        y1="51.8571"
        x2="-13"
        y2="-21.4286"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#28CCF0" />
        <stop offset="0.6986" stopColor="#799DFA" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoInvisible.defaultProps = { size: 24 };

NeetoInvisible.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
