/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoCrm = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3204_326)"
    />
    <g clipPath="url(#clip0_3204_326)">
      <g filter="url(#filter0_d_3204_326)">
        <path
          d="M15.2783 20.9125C14.5199 20.1541 13.2903 20.1541 12.5319 20.9125C11.7735 21.6709 11.7735 22.9005 12.5319 23.6589C13.2903 24.4173 14.5199 24.4173 15.2783 23.6589C16.0367 22.9005 16.0367 21.6709 15.2783 20.9125ZM16.8424 19.3484C15.2202 17.7262 12.59 17.7262 10.9678 19.3484C9.34554 20.9706 9.34554 23.6008 10.9678 25.223C12.59 26.8453 15.2202 26.8453 16.8424 25.223C18.4646 23.6008 18.4646 20.9706 16.8424 19.3484Z"
          fill="white"
          fillRule="evenodd"
          clipRule="evenodd"
        />
        <path
          d="M27.468 14.8176C26.7096 14.0592 25.48 14.0592 24.7216 14.8176C23.9632 15.5761 23.9632 16.8057 24.7216 17.5641C25.48 18.3225 26.7096 18.3225 27.468 17.5641C28.2264 16.8057 28.2264 15.5761 27.468 14.8176ZM29.0321 13.2535C27.4099 11.6313 24.7797 11.6313 23.1575 13.2535C21.5353 14.8758 21.5353 17.5059 23.1575 19.1282C24.7797 20.7504 27.4099 20.7504 29.0321 19.1282C30.6544 17.5059 30.6544 14.8758 29.0321 13.2535Z"
          fill="white"
          fillRule="evenodd"
          clipRule="evenodd"
        />
        <path
          d="M27.468 27.0074C26.7096 26.249 25.48 26.249 24.7216 27.0074C23.9632 27.7658 23.9632 28.9954 24.7216 29.7538C25.48 30.5122 26.7096 30.5122 27.468 29.7538C28.2264 28.9954 28.2264 27.7658 27.468 27.0074ZM29.0321 25.4433C27.4099 23.8211 24.7797 23.8211 23.1575 25.4433C21.5353 27.0655 21.5353 29.6957 23.1575 31.3179C24.7797 32.9402 27.4099 32.9402 29.0321 31.3179C30.6544 29.6957 30.6544 27.0655 29.0321 25.4433Z"
          fill="white"
          fillRule="evenodd"
          clipRule="evenodd"
        />
        <path
          d="M24.3723 17.0483C24.6455 17.5947 24.424 18.259 23.8777 18.5322L17.112 21.915C16.5657 22.1882 15.9013 21.9667 15.6281 21.4204C15.355 20.8741 15.5764 20.2097 16.1228 19.9366L22.8885 16.5537C23.4348 16.2805 24.0991 16.502 24.3723 17.0483Z"
          fill="white"
          fillRule="evenodd"
          clipRule="evenodd"
        />
        <path
          d="M15.6281 23.1513C15.9013 22.605 16.5657 22.3835 17.112 22.6567L23.8777 26.0395C24.424 26.3127 24.6455 26.977 24.3723 27.5234C24.0991 28.0697 23.4348 28.2912 22.8885 28.018L16.1228 24.6351C15.5764 24.362 15.355 23.6976 15.6281 23.1513Z"
          fill="white"
          fillRule="evenodd"
          clipRule="evenodd"
        />
      </g>
    </g>
    <defs>
      <filter
        id="filter0_d_3204_326"
        x="9.7511"
        y="12.0369"
        width="22.2377"
        height="22.5277"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.87" dy="1.16" />
        <feGaussianBlur stdDeviation="0.435" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3204_326"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3204_326"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3204_326"
        x1="40"
        y1="48.1429"
        x2="21.1215"
        y2="4.67289"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#609AF0" />
        <stop offset="1" stopColor="#6BD1F1" />
      </linearGradient>
      <clipPath id="clip0_3204_326">
        <rect
          width="27.4286"
          height="27.4286"
          fill="white"
          transform="translate(6.28571 8.57147)"
        />
      </clipPath>
    </defs>
  </svg>
);

NeetoCrm.defaultProps = { size: 24 };

NeetoCrm.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
