/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoPopups = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3193_170)"
    />
    <g filter="url(#filter0_d_3193_170)">
      <path
        d="M20.0001 32.5023L17.5878 30.1553H22.4124L20.0001 32.5023Z"
        fill="white"
      />
      <path
        d="M20 10.8571C25.365 10.8571 29.7143 15.2064 29.7143 20.5714V30.2857H10.2857V10.8571H20ZM15.6318 17.6376C15.3438 17.6376 15.1102 17.8711 15.1102 18.1591C15.1102 18.4472 15.3438 18.6807 15.6318 18.6807H24.2378C24.5258 18.6807 24.7593 18.4472 24.7593 18.1591C24.7593 17.8711 24.5258 17.6376 24.2378 17.6376H15.6318ZM15.1102 20.6366C15.1102 20.3485 15.3438 20.115 15.6318 20.115H24.2378C24.5258 20.115 24.7593 20.3485 24.7593 20.6366C24.7593 20.9247 24.5258 21.1582 24.2378 21.1582H15.6318C15.3438 21.1582 15.1102 20.9247 15.1102 20.6366ZM15.6318 22.7229C15.3438 22.7229 15.1102 22.9564 15.1102 23.2445C15.1102 23.5325 15.3438 23.766 15.6318 23.766H19.8044C20.0924 23.766 20.326 23.5325 20.326 23.2445C20.326 22.9564 20.0924 22.7229 19.8044 22.7229H15.6318Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3193_170"
        x="10.2857"
        y="10.8571"
        width="21.1429"
        height="23.6452"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3193_170"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3193_170"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3193_170"
        x1="40"
        y1="48.1429"
        x2="-6.85714"
        y2="-9.71428"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#59B9EF" />
        <stop offset="1" stopColor="#3EA8CA" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoPopups.defaultProps = { size: 24 };

NeetoPopups.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
