/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Neeto = ({ width, height, ...other }) => (
  <svg
    width={width}
    height={height}
    viewBox="0 0 632 122"
    fill="none"
    {...other}
  >
    <path
      d="M122 61C122 27.3107 94.6892 0 61 0H0V122H122V61Z"
      fill="url(#paint0_linear_3457_4142)"
    />
    <path
      d="M91.5002 8.174C109.935 18.6681 121.985 38.25 121.985 60.9793V111.487C120.948 103.557 114.726 96.9693 93.4978 73.8503C76.5154 55.3551 85.2171 22.4411 91.5002 8.174Z"
      fill="url(#paint1_linear_3457_4142)"
    />
    <path
      d="M91.5002 8.174C109.935 18.6681 121.985 38.25 121.985 60.9793V111.487C120.948 103.557 114.726 96.9693 93.4978 73.8503C76.5154 55.3551 85.2171 22.4411 91.5002 8.174Z"
      fill="url(#paint2_linear_3457_4142)"
    />
    <path
      d="M0 0H61C71.9099 0 82.594 2.928 91.5 8.174C95.5667 15.0222 99.3568 34.038 83.936 56.486C64.66 84.546 62.525 89.792 53.741 122H0V0Z"
      fill="url(#paint3_linear_3457_4142)"
    />
    <path
      d="M0 0H61C71.9099 0 81.74 2.745 91.5 8.174C95.5667 15.0222 99.3568 34.038 83.936 56.486C64.66 84.546 62.525 89.792 53.741 122H0V0Z"
      fill="url(#paint4_linear_3457_4142)"
    />
    <path
      d="M60.756 122C50.691 84.668 18.2797 76.0558 0 67.954V122H60.756Z"
      fill="url(#paint5_linear_3457_4142)"
      fillOpacity="0.4"
    />
    <path
      d="M178 31.6V122H197.334V50.81H223.492C237.939 50.81 249.65 62.4461 249.65 76.8V122H268.984V76.8C268.984 51.8367 248.617 31.6 223.492 31.6H178Z"
      fill="#11243E"
    />
    <path
      d="M347.956 69.3714C346.101 57.6099 338.887 48.944 324.458 48.944C311.058 48.944 301.784 56.368 299.312 69.3714H347.956ZM326.726 104.456C338.061 104.456 346.306 99.9157 351.254 95.1693L363.415 107.964C355.375 116.015 344.247 122 326.934 122C297.25 122 278.082 102.808 278.082 76.8045C278.082 51.0037 298.284 31.6 324.247 31.6C353.723 31.6 370.418 53.4783 368.981 83.8197H299.312C301.784 96.4111 310.853 104.456 326.726 104.456Z"
      fill="#11243E"
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M448.038 69.3714C446.184 57.6099 438.97 48.944 424.541 48.944C411.14 48.944 401.867 56.368 399.395 69.3714H448.038ZM426.808 104.456C438.143 104.456 446.389 99.9157 451.336 95.1693L463.498 107.964C455.457 116.015 444.33 122 427.016 122C397.333 122 378.165 102.808 378.165 76.8045C378.165 51.0037 398.367 31.6 424.33 31.6C453.805 31.6 470.501 53.4783 469.063 83.8197H399.395C401.867 96.4111 410.935 104.456 426.808 104.456Z"
      fill="#11243E"
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M478.247 32.3793H493.503V9H512.892V32.3793H531.918V49.9038H512.892V85.4145C512.892 101.478 515.402 103.974 531.918 103.974V122H529.047C501.76 122 493.503 113.432 493.503 85.5952V49.9038H478.247V32.3793Z"
      fill="#11243E"
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <path
      d="M613.419 76.8015C613.419 61.5017 601.494 48.985 586.421 48.985C571.344 48.985 559.597 61.5017 559.597 76.8015C559.597 92.0983 571.344 104.615 586.421 104.615C601.494 104.615 613.419 92.0983 613.419 76.8015ZM541.016 76.8015C541.016 51.4191 561.176 31.6 586.421 31.6C611.665 31.6 632 51.4191 632 76.8015C632 102.008 611.665 122 586.421 122C561.176 122 541.016 102.008 541.016 76.8015Z"
      fill="#11243E"
      fillRule="evenodd"
      clipRule="evenodd"
    />
    <defs>
      <linearGradient
        id="paint0_linear_3457_4142"
        x1="-3.37555e-07"
        y1="5.307"
        x2="112.179"
        y2="130.235"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8BBEFF" />
        <stop offset="0.612688" stopColor="#8C9CF5" />
        <stop offset="0.779469" stopColor="#8FA1F2" />
        <stop offset="1" stopColor="#98ACF4" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_3457_4142"
        x1="19.0908"
        y1="-0.288133"
        x2="17.9933"
        y2="157.297"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6565E3" />
        <stop offset="0.489583" stopColor="#8A99EE" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_3457_4142"
        x1="68.0082"
        y1="64.1072"
        x2="78.5257"
        y2="130.584"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6C6CDE" stopOpacity="0" />
        <stop offset="1" stopColor="#8C96EB" />
      </linearGradient>
      <linearGradient
        id="paint3_linear_3457_4142"
        x1="110.812"
        y1="10.553"
        x2="79.0829"
        y2="126.976"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8684ED" />
        <stop offset="0.510809" stopColor="#8C9DF6" />
        <stop offset="0.767213" stopColor="#8B94F2" stopOpacity="0" />
      </linearGradient>
      <linearGradient
        id="paint4_linear_3457_4142"
        x1="-9.7039"
        y1="-17.202"
        x2="22.6851"
        y2="52.4367"
        gradientUnits="userSpaceOnUse"
      >
        <stop offset="0.197917" stopColor="#AF84FF" />
        <stop offset="0.9375" stopColor="#8B94F2" stopOpacity="0" />
      </linearGradient>
      <linearGradient
        id="paint5_linear_3457_4142"
        x1="26.84"
        y1="71.736"
        x2="26.962"
        y2="107.787"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#8CA7F8" />
        <stop offset="0.287723" stopColor="#8CA4F8" />
        <stop offset="0.614583" stopColor="#8BBFFE" />
        <stop offset="1" stopColor="#84CAFF" />
      </linearGradient>
    </defs>
  </svg>
);

Neeto.defaultProps = { width: "auto", height: 20 };

Neeto.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
