/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Microsoft = ({ size, ...other }) => (
  <svg viewBox="0 0 200 200" height={size} width={size} {...other}>
    <rect x="20" y="20" width="80" height="80" fill="#F65314" />
    <rect x="120" y="20" width="80" height="80" fill="#7CBB00" />
    <rect x="20" y="120" width="80" height="80" fill="#00A4EF" />
    <rect x="120" y="120" width="80" height="80" fill="#FFBB00" />
  </svg>
);

Microsoft.defaultProps = { size: 24 };

Microsoft.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
