/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoReview = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3193_171)"
    />
    <g filter="url(#filter0_d_3193_171)">
      <path
        d="M27.5527 22.21C26.3275 20.9848 24.341 20.9848 23.1157 22.21C21.8905 23.4353 21.8905 25.4218 23.1157 26.6471C24.3173 27.8487 26.2511 27.8718 27.481 26.7166C27.4947 26.7003 27.5093 26.6845 27.5246 26.6691C27.5433 26.6505 27.5627 26.633 27.5827 26.6167C28.7779 25.3892 28.7679 23.4252 27.5527 22.21ZM29.0952 27.1684C30.4244 25.3487 30.2673 22.782 28.624 21.1387C26.8071 19.3218 23.8613 19.3218 22.0444 21.1387C20.2275 22.9557 20.2275 25.9014 22.0444 27.7184C23.6702 29.3441 26.1998 29.5151 28.0157 28.2315L30.4209 30.6367C30.7167 30.9325 31.1964 30.9325 31.4922 30.6367C31.788 30.3409 31.788 29.8612 31.4922 29.5654L29.0952 27.1684Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
      <path
        d="M14.2975 26.4547L17.7334 29.8906L20.7429 26.8812C19.6224 24.9092 19.903 22.3572 21.5845 20.6757C23.0211 19.2391 25.0932 18.8251 26.896 19.4337V16.1468C26.896 15.2355 26.534 14.3616 25.8896 13.7172C25.2453 13.0728 24.3713 12.7108 23.4601 12.7108H12.0068C11.0956 12.7108 10.2216 13.0728 9.57725 13.7172C8.93288 14.3616 8.57088 15.2355 8.57088 16.1468V23.0187C8.57088 23.93 8.93288 24.8039 9.57725 25.4483C10.2216 26.0927 11.0956 26.4547 12.0068 26.4547H14.2975ZM12.3013 17.1986C12.3013 16.7804 12.6404 16.4413 13.0586 16.4413H20.9123C21.3305 16.4413 21.6696 16.7804 21.6696 17.1986C21.6696 17.6169 21.3305 17.9559 20.9123 17.9559H13.0586C12.6404 17.9559 12.3013 17.6169 12.3013 17.1986ZM13.0586 19.2462C12.6404 19.2462 12.3013 19.5852 12.3013 20.0035C12.3013 20.4217 12.6404 20.7608 13.0586 20.7608H16.4245C16.8427 20.7608 17.1818 20.4217 17.1818 20.0035C17.1818 19.5852 16.8427 19.2462 16.4245 19.2462H13.0586Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3193_171"
        x="8.57088"
        y="12.7108"
        width="24.8575"
        height="20.1478"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3193_171"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3193_171"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3193_171"
        x1="40"
        y1="48.1429"
        x2="-6.85714"
        y2="-9.71428"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#59CBEF" />
        <stop offset="1" stopColor="#54CCAF" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoReview.defaultProps = { size: 24 };

NeetoReview.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
