/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoPlanner = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3204_322)"
    />
    <rect
      x="6"
      y="8"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="11.8205"
      y="8"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="17.641"
      y="8"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="23.4615"
      y="8"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="6.00003"
      y="13.8204"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="11.8205"
      y="13.8204"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="17.641"
      y="13.8204"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="6.00003"
      y="19.641"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="11.8205"
      y="19.641"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <rect
      x="6.00003"
      y="25.4615"
      width="5.17377"
      height="5.17377"
      rx="1.29344"
      fill="white"
    />
    <defs>
      <linearGradient
        id="paint0_linear_3204_322"
        x1="20"
        y1="0"
        x2="20"
        y2="40"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#4DC8C3" />
        <stop offset="1" stopColor="#52A9C6" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoPlanner.defaultProps = { size: 24 };

NeetoPlanner.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
