/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoWireframe = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3204_332)"
    />
    <g filter="url(#filter0_d_3204_332)">
      <rect
        x="17.015"
        y="11.7145"
        width="12.9849"
        height="5.22383"
        rx="0.511727"
        fill="white"
      />
      <rect
        x="10.0001"
        y="18.7294"
        width="12.9849"
        height="12.9849"
        rx="0.511727"
        fill="white"
      />
      <circle cx="12.612" cy="14.3263" r="2.61191" fill="white" />
      <rect
        x="24.7761"
        y="31.7142"
        width="12.9849"
        height="5.22383"
        rx="0.511727"
        transform="rotate(-90 24.7761 31.7142)"
        fill="white"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3204_332"
        x="10.0001"
        y="11.7144"
        width="21.7141"
        height="21.9999"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3204_332"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3204_332"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3204_332"
        x1="43.1429"
        y1="51.8571"
        x2="6.28572"
        y2="-3.57143"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6A67E8" />
        <stop offset="0.6986" stopColor="#B49AFC" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoWireframe.defaultProps = { size: 24 };

NeetoWireframe.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
