/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoForm = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <g clipPath="url(#clip0_3083_349)">
      <path
        d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
        fill="url(#paint0_linear_3083_349)"
      />
      <rect
        x="16.0052"
        y="19.6805"
        width="13.7881"
        height="3.7604"
        rx="1.8802"
        fill="white"
      />
      <rect
        x="16.0052"
        y="25.9479"
        width="10.6545"
        height="3.7604"
        rx="1.8802"
        fill="white"
      />
      <rect
        x="16.0052"
        y="13.4132"
        width="10.0277"
        height="3.7604"
        rx="1.8802"
        fill="white"
      />
      <circle cx="12.2449" cy="15.2934" r="1.8802" fill="white" />
      <circle cx="12.2449" cy="21.5607" r="1.8802" fill="white" />
      <circle cx="12.2449" cy="27.8281" r="1.8802" fill="white" />
    </g>
    <defs>
      <linearGradient
        id="paint0_linear_3083_349"
        x1="21.3084"
        y1="56.0748"
        x2="21.1215"
        y2="4.67289"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#E26682" />
        <stop offset="1" stopColor="#FE8072" />
      </linearGradient>
      <clipPath id="clip0_3083_349">
        <rect width="40" height="40" fill="white" />
      </clipPath>
    </defs>
  </svg>
);

NeetoForm.defaultProps = { size: 24 };

NeetoForm.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
