/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const Neeto = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <mask
      id="mask0_3193_178"
      style={{maskType: "alpha"}}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="40"
      height="40"
    >
      <g style={{mixBlendMode:"multiply"}}>
        <path
          d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
          fill="url(#pattern0)"
        />
      </g>
    </mask>
    <g mask="url(#mask0_3193_178)">
      <rect
        x="-0.335663"
        y="-3.02509"
        width="45.3782"
        height="45.3782"
        fill="url(#pattern1)"
      />
    </g>
    <defs>
      <pattern
        id="pattern0"
        patternContentUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <use transform="matrix(-0.00347797 0 0 0.0033515 1.54716 -0.256813)" />
      </pattern>
      <pattern
        id="pattern1"
        patternContentUnits="objectBoundingBox"
        width="1"
        height="1"
      >
        <use transform="scale(0.000434783)" />
      </pattern>
      <image id="image0_3193_178" width="500" height="375" />
      <image id="image1_3193_178" width="2300" height="2300" />
    </defs>
  </svg>
);

Neeto.defaultProps = { size: 24 };

Neeto.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
