/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoDesk = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <g clipPath="url(#clip0_3083_350)">
      <path
        d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
        fill="url(#paint0_linear_3083_350)"
      />
      <g filter="url(#filter0_d_3083_350)">
        <path
          d="M9.51115 20.3412H13.7424C14.9108 20.3412 15.858 21.2796 15.858 22.4372V25.5811C15.858 27.3175 14.4372 28.7251 12.6846 28.7251C10.932 28.7251 9.51115 27.3175 9.51115 25.5811V20.3412Z"
          fill="white"
        />
        <path
          d="M24.3206 22.4372C24.3206 21.2796 25.2677 20.3412 26.4362 20.3412H30.6674V25.5811C30.6674 27.3175 29.2466 28.7251 27.494 28.7251C25.7413 28.7251 24.3206 27.3175 24.3206 25.5811V22.4372Z"
          fill="white"
        />
        <path
          d="M9.56338 20.3412C10.0941 15.0454 14.6042 10.9093 20.0893 10.9093C25.5744 10.9093 30.0845 15.0454 30.6152 20.3412H28.4863C27.9658 16.2055 24.4048 13.0053 20.0893 13.0053C15.7738 13.0053 12.2128 16.2055 11.6923 20.3412H9.56338Z"
          fill="white"
        />
      </g>
    </g>
    <defs>
      <filter
        id="filter0_d_3083_350"
        x="9.51115"
        y="10.9093"
        width="22.4398"
        height="19.0993"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.641768" dy="0.641768" />
        <feGaussianBlur stdDeviation="0.320884" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.08 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3083_350"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3083_350"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3083_350"
        x1="21.3084"
        y1="56.0748"
        x2="21.1215"
        y2="4.67289"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FD9437" />
        <stop offset="1" stopColor="#FFD55C" />
      </linearGradient>
      <clipPath id="clip0_3083_350">
        <rect width="40" height="40" fill="white" />
      </clipPath>
    </defs>
  </svg>
);

NeetoDesk.defaultProps = { size: 24 };

NeetoDesk.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
