/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export const NeetoStore = ({ size, ...other }) => (
  <svg width={size} height={size} viewBox="0 0 40 40" fill="none" {...other}>
    <path
      d="M40 20C40 8.95431 31.0457 0 20 0H0V40H40V20Z"
      fill="url(#paint0_linear_3193_168)"
    />
    <g filter="url(#filter0_d_3193_168)">
      <path
        d="M20 10.2857C25.365 10.2857 29.7143 14.6349 29.7143 20V29.7143H10.2857V10.2857H20ZM15.8552 15.0781C15.8552 14.6489 15.5073 14.3009 15.0781 14.3009C14.6489 14.3009 14.3009 14.6489 14.3009 15.0781C14.3009 18.2256 16.8525 20.7771 20 20.7771C23.1475 20.7771 25.699 18.2256 25.699 15.0781C25.699 14.6489 25.3511 14.3009 24.9219 14.3009C24.4927 14.3009 24.1447 14.6489 24.1447 15.0781C24.1447 17.3672 22.2891 19.2228 20 19.2228C17.7109 19.2228 15.8552 17.3672 15.8552 15.0781Z"
        fill="white"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_3193_168"
        x="10.2857"
        y="10.2857"
        width="21.1428"
        height="21.4286"
        filterUnits="userSpaceOnUse"
        colorInterpolationFilters="sRGB"
      >
        <feFlood result="BackgroundImageFix" floodOpacity="0" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="0.857143" dy="1.14286" />
        <feGaussianBlur stdDeviation="0.428571" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_3193_168"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_3193_168"
          result="shape"
        />
      </filter>
      <linearGradient
        id="paint0_linear_3193_168"
        x1="43.1429"
        y1="51.8571"
        x2="6.28572"
        y2="-3.57143"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#3C5BFF" />
        <stop offset="0.6986" stopColor="#55ABE9" />
      </linearGradient>
    </defs>
  </svg>
);

NeetoStore.defaultProps = { size: 24 };

NeetoStore.propTypes = {
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
