name: "Publish npm package"
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  publish:
    name: "Publish"
    runs-on: macos-latest
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    steps:
      - uses: actions/checkout@v2.2.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Bump version
        run: yarn version --patch --no-git-tag-version
      - uses: EndBug/add-and-commit@v7
        with:
          branch: master
          message: 'New version release'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install
      - name: "Publish"
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}