name: "Publish npm package"
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: "Publish"
    runs-on: macos-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install
      - name: "Publish"
        uses: JS-DevTools/npm-publish@v1
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}