name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS LTS version
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"

      - name: Setup the project
        run: yarn install

      - name: Generate production build
        run: yarn build

      - name: Publish the package on NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}

  publish_native:
    name: Publish Native Package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS LTS version
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.0"

      - name: Generate native icons
        working-directory: ./native
        run: yarn generate

      - name: Publish the native package on NPM
        working-directory: ./native
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc && yarn publish --access public

